#line 1 "lexer.flex.c"

#line 3 "lexer.flex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 117
#define YY_END_OF_BUFFER 118
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[265] =
    {   0,
        0,    0,  111,  111,    0,    0,  118,  117,  116,   68,
       84,  108,   41,   60,   71,   72,   39,   37,   81,   38,
       80,   40,  102,  102,   82,   83,   46,   53,   45,   79,
      115,   75,   76,   62,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,   73,   61,   74,   63,   53,  111,  111,   85,  101,
      100,  117,   44,  108,   58,   66,   42,   56,   54,   55,
       69,   57,    0,  104,    0,    0,    0,    0,    0,  102,
        0,   64,   48,   43,   47,   65,    0,  113,  115,  112,
      112,  112,  112,  112,  112,  112,  112,    9,  112,  112,

      112,  112,  112,   10,   17,  112,  112,  112,  112,   22,
      112,  112,  112,  112,  112,  112,  112,  112,   67,    0,
      111,  111,   85,   96,   97,   95,   87,   88,   93,   91,
       86,   92,   94,   89,   90,   99,   59,   70,  107,    0,
      106,  103,    0,  107,  105,  102,   49,   50,  114,  113,
      112,    2,  112,  112,  112,  112,    7,  112,   13,  112,
      112,  112,  112,   16,  112,  112,   20,   21,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,    0,  111,   97,   99,   98,    0,  104,    0,  103,
        0,  107,    0,    0,  114,  112,  112,  112,    5,  112,

      112,   11,  112,  112,   51,  112,  112,  112,   19,   23,
      112,  112,  112,   27,  112,   29,   30,  112,  112,  112,
       34,  112,  112,    0,  110,   97,   98,  107,  106,  103,
      107,  105,    1,    3,    4,    6,  112,   12,  112,  112,
       15,  112,  112,   25,  112,   28,   31,  112,   33,   35,
       36,    0,  110,  112,   14,   52,   18,   24,   26,   32,
      109,  112,    8,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    1,    6,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   27,   29,   30,   27,
       31,   31,   31,   31,   31,   31,   31,   31,   32,   31,
       31,   31,   31,   31,   31,   31,   31,   33,   31,   31,
       34,   35,   36,   37,   38,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   48,   49,   50,   51,   52,
       53,   54,   55,   56,   57,   58,   59,   60,   61,   62,
       63,   48,   64,   65,   66,   67,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[68] =
    {   0,
        1,    2,    1,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    4,    4,    4,    4,    1,
        1,    1,    1,    1,    1,    5,    4,    4,    4,    4,
        6,    6,    6,    1,    7,    1,    1,    8,    9,    9,
        9,    9,    9,    9,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[281] =
    {   0,
        0,  469,  489,   66,   67,   68,  490,  493,  493,  466,
      493,    0,  465,  480,  493,  493,   63,  463,  493,  462,
      470,  460,   90,   62,  493,  493,   52,  459,   59,  455,
        0,  493,  493,  493,    0,   35,   34,   45,   45,   41,
       58,   57,  427,   74,  423,  435,   51,   68,  425,  430,
      428,  493,  409,  493,  493,   76,    0,  430,    0,  493,
      493,  149,  493,    0,  493,  493,  449,  493,  493,  493,
      457,  493,  118,  122,   96,  127,  137,  141,    0,  156,
      145,  493,  446,  446,  493,  493,    0,    0,    0,    0,
      421,  425,  421,  422,  407,  424,  418,    0,  404,   84,

       92,  410,  403,    0,    0,  409,  386,  397,  388,    0,
      138,  395,  388,  398,  381,  127,   82,  396,  493,  392,
        0,  381,    0,  493,  165,  493,  493,  493,  493,  493,
      493,  493,  493,  493,  493,  196,  493,  493,  203,  186,
      162,  211,  199,  226,  387,  236,  493,  493,    0,    0,
      385,    0,  373,  379,  370,  355,  364,  144,    0,  351,
      381,  363,  344,    0,  333,  330,    0,    0,  333,  341,
       72,  336,  333,  323,  323,  302,  301,  296,  290,  291,
      290,  294,  296,  240,  264,    0,  243,  251,  181,  259,
      254,  282,  268,    0,    0,  280,  282,  284,    0,  275,

      278,    0,  285,  272,  493,  272,  278,  269,    0,    0,
      259,  239,  234,    0,  232,    0,    0,  221,  206,  201,
        0,  205,  205,  187,    0,  493,  493,  293,  279,  297,
      308,  194,    0,    0,    0,    0,  188,    0,  167,  183,
        0,  147,  133,    0,  119,    0,    0,  111,    0,    0,
        0,   97,    0,  105,    0,  493,    0,    0,    0,    0,
      493,   90,  493,  493,  346,  355,  364,  369,  375,  381,
      390,  399,  405,  407,  413,  422,  428,  434,  440,  449
    } ;

static const flex_int16_t yy_def[281] =
    {   0,
      264,    1,  265,  265,  266,  266,  264,  264,  264,  264,
      264,  267,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  268,
      269,  264,  264,  264,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  264,  264,  264,  264,  264,  271,  271,  272,  264,
      264,  264,  264,  267,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  273,  264,
      264,  264,  264,  264,  264,  264,  274,  275,  269,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,

      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  264,  264,
      271,  271,  272,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  276,  264,  264,  264,  264,
      264,  264,  264,  264,  273,  264,  264,  264,  277,  275,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  264,  271,  264,  276,  278,  264,  264,  264,  264,
      264,  264,  264,  279,  277,  270,  270,  270,  270,  270,

      270,  270,  270,  270,  264,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  264,  280,  264,  264,  264,  264,  264,
      264,  279,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  270,  270,  270,  270,  270,  270,  270,  270,  270,
      270,  264,  280,  270,  270,  264,  270,  270,  270,  270,
      264,  270,  264,    0,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264
    } ;

static const flex_int16_t yy_nxt[561] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   24,   24,   25,
       26,   27,   28,   29,    8,   30,   31,   31,   31,   31,
       31,   31,   31,   32,    8,   33,   34,   35,   36,   37,
       38,   39,   40,   41,   35,   35,   42,   35,   35,   35,
       43,   44,   45,   35,   35,   46,   47,   48,   49,   35,
       50,   35,   51,   52,   53,   54,   55,    8,   60,   60,
       61,   61,   67,   82,   83,   73,   93,   80,   80,   80,
       80,   85,   86,   95,   91,   68,   92,   97,   58,   94,
       99,   77,  100,  112,   96,  101,  102,   98,   84,   81,

      104,   62,   62,   73,   77,   74,   74,   74,  105,  113,
      103,  141,  141,  114,  263,  120,  107,   75,   76,   77,
      108,   78,   79,  115,  179,  159,  109,  212,  180,   75,
      213,   76,   77,  139,  139,  139,  139,   74,   74,   74,
      160,  161,   78,  142,  142,  142,  262,  143,  261,  143,
      162,   79,  124,  144,  144,  144,   74,   74,   74,  140,
      146,  146,  146,  146,  125,  125,  125,  260,  176,   73,
      259,   80,   80,   80,   80,  258,  177,  141,  141,  169,
      184,  184,  184,  126,  178,   77,  202,  127,  128,  257,
      203,  129,  130,   81,  170,  171,  229,  229,   77,  189,

      131,  188,  188,  188,  132,  133,  134,  256,  135,  255,
      136,  186,  186,  186,  186,  144,  144,  144,  139,  139,
      139,  139,  186,  186,  186,  186,  190,  190,  190,  190,
      254,  194,   77,  252,  186,  186,  186,  186,  186,  186,
      187,  192,  192,  192,  192,   77,  251,  250,  191,   73,
      249,  146,  146,  146,  146,  226,  226,  226,  228,  228,
      228,  228,  248,  193,  247,   77,  188,  188,  188,  230,
      230,  230,  230,   81,  190,  190,  190,  190,   77,  264,
      264,  264,  264,  231,  231,  231,  231,  246,  140,  245,
      264,  264,  264,  264,  229,  229,  191,  192,  192,  192,

      192,  244,  264,  264,  264,  264,  264,  264,  228,  228,
      228,  228,  230,  230,  230,  230,  189,  243,  242,  193,
      241,  240,   77,  231,  231,  231,  231,  239,  238,  237,
      187,  236,  235,  234,  191,   77,  233,  225,  224,  223,
      222,  221,  220,  219,  218,  193,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   64,  217,   64,   64,   64,   64,
       64,   64,   64,   88,  216,  215,   88,   88,   89,  214,
       89,  211,   89,   89,   90,  210,   90,  209,   90,   90,
      121,  208,  121,  121,  121,  121,  121,  121,  121,  123,

      207,  206,  123,  123,  123,  205,  123,  123,  145,  204,
      201,  200,  199,  145,  149,  149,  150,  198,  150,  197,
      150,  150,  185,  196,  194,  185,  185,  185,  185,  185,
      185,  195,  183,  195,  182,  195,  195,  227,  181,  175,
      174,  173,  227,  232,  172,  168,  167,  166,  232,  253,
      165,  253,  253,  253,  253,  253,  253,  253,  164,  163,
      158,  157,  156,  155,  154,  153,  152,  151,  148,  147,
      138,  137,  122,  119,  118,  117,  116,  111,  110,  106,
       87,   84,   72,   71,   70,   69,   66,   65,   63,  264,
        8,   56,    7,  264,  264,  264,  264,  264,  264,  264,

      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264
    } ;

static const flex_int16_t yy_chk[561] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    4,    5,    6,
        5,    6,   17,   27,   27,   24,   37,   24,   24,   24,
       24,   29,   29,   38,   36,   17,   36,   39,    4,   37,
       40,   24,   40,   47,   38,   40,   41,   39,   56,   24,

       42,    5,    6,   23,   24,   23,   23,   23,   42,   47,
       41,   75,   75,   48,  262,   56,   44,   23,   23,   23,
       44,   23,   23,   48,  117,  100,   44,  171,  117,   23,
      171,   23,   23,   73,   73,   73,   73,   74,   74,   74,
      100,  101,   23,   76,   76,   76,  254,   77,  252,   77,
      101,   23,   62,   77,   77,   77,   78,   78,   78,   74,
       81,   81,   81,   81,   62,   62,   62,  248,  116,   80,
      245,   80,   80,   80,   80,  243,  116,  141,  141,  111,
      125,  125,  125,   62,  116,   80,  158,   62,   62,  242,
      158,   62,   62,   80,  111,  111,  189,  189,   80,  141,

       62,  140,  140,  140,   62,   62,   62,  240,   62,  239,
       62,  136,  136,  136,  136,  143,  143,  143,  139,  139,
      139,  139,  136,  136,  136,  136,  142,  142,  142,  142,
      237,  232,  139,  224,  136,  136,  136,  136,  136,  136,
      139,  144,  144,  144,  144,  139,  223,  222,  142,  146,
      220,  146,  146,  146,  146,  184,  184,  184,  187,  187,
      187,  187,  219,  144,  218,  146,  188,  188,  188,  191,
      191,  191,  191,  146,  190,  190,  190,  190,  146,  185,
      185,  185,  185,  193,  193,  193,  193,  215,  188,  213,
      185,  185,  185,  185,  229,  229,  190,  192,  192,  192,

      192,  212,  185,  185,  185,  185,  185,  185,  228,  228,
      228,  228,  230,  230,  230,  230,  229,  211,  208,  192,
      207,  206,  228,  231,  231,  231,  231,  204,  203,  201,
      228,  200,  198,  197,  230,  228,  196,  183,  182,  181,
      180,  179,  178,  177,  176,  231,  265,  265,  265,  265,
      265,  265,  265,  265,  265,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  267,  175,  267,  267,  267,  267,
      267,  267,  267,  268,  174,  173,  268,  268,  269,  172,
      269,  170,  269,  269,  270,  169,  270,  166,  270,  270,
      271,  165,  271,  271,  271,  271,  271,  271,  271,  272,

      163,  162,  272,  272,  272,  161,  272,  272,  273,  160,
      157,  156,  155,  273,  274,  274,  275,  154,  275,  153,
      275,  275,  276,  151,  145,  276,  276,  276,  276,  276,
      276,  277,  122,  277,  120,  277,  277,  278,  118,  115,
      114,  113,  278,  279,  112,  109,  108,  107,  279,  280,
      106,  280,  280,  280,  280,  280,  280,  280,  103,  102,
       99,   97,   96,   95,   94,   93,   92,   91,   84,   83,
       71,   67,   58,   53,   51,   50,   49,   46,   45,   43,
       30,   28,   22,   21,   20,   18,   14,   13,   10,    7,
        3,    2,  264,  264,  264,  264,  264,  264,  264,  264,

      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264,
      264,  264,  264,  264,  264,  264,  264,  264,  264,  264
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[118] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 6 "lexer.l"
	#include <stdio.h>

    void remove_char_from_str(const char * str, char * dest, char deleted_char);
    int binstr_to_dec(const char * str);
#line 690 "lexer.flex.c"

#line 692 "lexer.flex.c"

#define INITIAL 0
#define ML_COMMENT 1
#define STRING 2

/*windows compatibility case*/
#include <io.h>
#define isatty _isatty
#define fileno _fileno
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 22 "lexer.l"



#line 26 "lexer.l"
    int num;
    float real_num;
    char temp1[100];
    char temp2[100];
    char comment[1000];
    char string[1000];


#line 924 "lexer.flex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 265 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 264 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 34 "lexer.l"
{ printf("Found ALIAS_KEYWORD\n"); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 35 "lexer.l"
{ printf("Found AND_KEYWORD\n"); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 36 "lexer.l"
{ printf("Found BEGIN_KEYWORD\n"); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 37 "lexer.l"
{ printf("Found BREAK_KEYWORD\n"); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 38 "lexer.l"
{ printf("Found CASE_KEYWORD\n"); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 39 "lexer.l"
{ printf("Found CLASS_KEYWORD\n"); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 40 "lexer.l"
{ printf("Found DEF_KEYWORD\n"); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 41 "lexer.l"
{ printf("Found DEFINED_KEYWORD\n"); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 42 "lexer.l"
{ printf("Found DO_KEYWORD\n"); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 43 "lexer.l"
{ printf("Found IF_KEYWORD\n"); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 44 "lexer.l"
{ printf("Found ELSE_KEYWORD\n"); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 45 "lexer.l"
{ printf("Found ELSIF_KEYWORD\n"); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 46 "lexer.l"
{ printf("Found END_KEYWORD\n"); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 47 "lexer.l"
{ printf("Found ENSURE_KEYWORD\n"); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 48 "lexer.l"
{ printf("Found FALSE_KEYWORD\n"); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 49 "lexer.l"
{ printf("Found FOR_KEYWORD\n"); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 50 "lexer.l"
{ printf("Found IN_KEYWORD\n"); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 51 "lexer.l"
{ printf("Found MODULE_KEYWORD\n"); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 52 "lexer.l"
{ printf("Found NEXT_KEYWORD\n"); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 53 "lexer.l"
{ printf("Found NIL_KEYWORD\n"); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 54 "lexer.l"
{ printf("Found NOT_KEYWORD\n"); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 55 "lexer.l"
{ printf("Found OR_KEYWORD\n"); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 56 "lexer.l"
{ printf("Found REDO_KEYWORD\n"); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 57 "lexer.l"
{ printf("Found RESCUE_KEYWORD\n"); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 58 "lexer.l"
{ printf("Found RETRY_KEYWORD\n"); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 59 "lexer.l"
{ printf("Found RETURN_KEYWORD\n"); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 60 "lexer.l"
{ printf("Found SELF_KEYWORD\n"); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 61 "lexer.l"
{ printf("Found SUPER_KEYWORD\n"); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 62 "lexer.l"
{ printf("Found THEN_KEYWORD\n"); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 63 "lexer.l"
{ printf("Found TRUE_KEYWORD\n"); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 64 "lexer.l"
{ printf("Found UNDEF_KEYWORD\n"); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 65 "lexer.l"
{ printf("Found UNLESS_KEYWORD\n"); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 66 "lexer.l"
{ printf("Found UNTIL_KEYWORD\n"); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 67 "lexer.l"
{ printf("Found WHEN_KEYWORD\n"); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 68 "lexer.l"
{ printf("Found WHILE_KEYWORD\n"); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 69 "lexer.l"
{ printf("Found YIELD_KEYWORD\n"); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 71 "lexer.l"
{ printf("Found ARITHMETIC_PLUS_OP\n"); }   
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 72 "lexer.l"
{ printf("Found ARITHMETIC_MINUS_OP\n"); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 73 "lexer.l"
{ printf("Found ARITHMETIC_MUL_OP\n"); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 74 "lexer.l"
{ printf("Found ARITHMETIC_DIV_OP\n"); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 75 "lexer.l"
{ printf("Found ARITHMETIC_MOD_OP\n"); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 76 "lexer.l"
{ printf("Found ARITHMETIC_POW_OP\n"); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 78 "lexer.l"
{ printf("Found EQL_OP\n"); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 79 "lexer.l"
{ printf("Found NOT_EQL_OP\n"); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 80 "lexer.l"
{ printf("Found GREATER_OP\n"); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 81 "lexer.l"
{ printf("Found LESS_OP\n"); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 82 "lexer.l"
{ printf("Found GREATER_OR_EQL_OP\n"); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 83 "lexer.l"
{ printf("Found LESS_OR_EQL_OP\n"); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 84 "lexer.l"
{ printf("Found COMB_COMPRASION_OP\n"); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 85 "lexer.l"
{ printf("Found CASE_EQL_OP\n"); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 86 "lexer.l"
{ printf("Found RECEIVER_EQL_OP\n"); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 87 "lexer.l"
{ printf("Found OBJ_ID_EQL_OP\n"); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 89 "lexer.l"
{ printf("Found ASSIGN_OP\n"); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 90 "lexer.l"
{ printf("Found ADD_ASSIGN_OP\n"); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 91 "lexer.l"
{ printf("Found SUB_ASSIGN_OP\n"); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 92 "lexer.l"
{ printf("Found MUL_ASSIGN_OP\n"); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 93 "lexer.l"
{ printf("Found DIV_ASSIGN_OP\n"); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 94 "lexer.l"
{ printf("Found MOD_ASSIGN_OP\n"); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 95 "lexer.l"
{ printf("Found POW_ASSIGN_OP\n"); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 97 "lexer.l"
{ printf("Found BIN_AND_OP\n"); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 98 "lexer.l"
{ printf("Found BIN_OR_OP\n"); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 99 "lexer.l"
{ printf("Found BIN_XOR_OP\n"); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 100 "lexer.l"
{ printf("Found BIN_ONES_COMPLEMENT_OP\n"); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 101 "lexer.l"
{ printf("Found BIN_LEFT_SHIFT_OP\n"); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 102 "lexer.l"
{ printf("Found BIN_RIGHT_SHIFT_OP\n"); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 104 "lexer.l"
{ printf("Found LOGICAL_AND_OP\n"); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 105 "lexer.l"
{ printf("Found LOGICAL_OR_OP\n"); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 106 "lexer.l"
{ printf("Found LOGICAL_NOT_OP\n"); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 108 "lexer.l"
{ printf("Found INCLUSIVE_RANGE_OP\n"); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 109 "lexer.l"
{ printf("Found EXCLUSIVE_RANGE_OP\n"); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 111 "lexer.l"
{ printf("Found OPEN_ROUND_BRACKET\n"); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 112 "lexer.l"
{ printf("Found CLOSE_ROUND_BRACKET\n"); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 113 "lexer.l"
{ printf("Found OPEN_CURLY_BRACKET\n"); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 114 "lexer.l"
{ printf("Found CLOSE_CURLY_BRACKET\n"); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 115 "lexer.l"
{ printf("Found OPEN_SQUARE_BRACKET\n"); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 116 "lexer.l"
{ printf("Found CLOSE_SQUARE_BRACKET\n"); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 117 "lexer.l"
{ printf("Found OPEN_ANGLE_BRACKET\n"); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 118 "lexer.l"
{ printf("Found CLOSE_ANGLE_BRACKET\n"); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 119 "lexer.l"
{ printf("Found COMMERCIAL_AT\n"); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 121 "lexer.l"
{ printf("Found DOT SYMBOL\n"); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 122 "lexer.l"
{ printf("Found COMMA SYMBOOL\n"); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 123 "lexer.l"
{ printf("Found COLON SYMBOL\n"); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 124 "lexer.l"
{ printf("Found SEMICOLON SYMBOL\n"); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 126 "lexer.l"
{ 
                string[0] = 0; 
                BEGIN(STRING);    
            }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 131 "lexer.l"
{ strcat(string, yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 132 "lexer.l"
{ strcat(string, "\n"); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 133 "lexer.l"
{ strcat(string, "\a"); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 134 "lexer.l"
{ strcat(string, "\b"); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 135 "lexer.l"
{ strcat(string, "\t"); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 136 "lexer.l"
{ strcat(string, "\v"); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 137 "lexer.l"
{ strcat(string, "\f"); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 138 "lexer.l"
{ strcat(string, "\r"); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 139 "lexer.l"
{ strcat(string, "\e"); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 140 "lexer.l"
{ strcat(string, " "); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 141 "lexer.l"
{ strcat(string, "\\"); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 142 "lexer.l"
{ strcat(string, "\""); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 143 "lexer.l"
{ 
                                sscanf(yytext + 1, "%o", &num);
                                temp1[0] = (char) num;
                                temp1[1] = 0;
                                strcat(string, temp1);
                            }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 150 "lexer.l"
{ 
                                sscanf(yytext + 2, "%x", &num);
                                temp1[0] = (char) num;
                                temp1[1] = 0;
                                strcat(string, temp1);
                            }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 156 "lexer.l"
{ printf("ERROR: Invalid hex escape \n"); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 158 "lexer.l"
{ 
                printf("Found string %s \n", string);
                BEGIN(INITIAL);
            }
	YY_BREAK
case 101:
/* rule 101 can match eol */
YY_RULE_SETUP
#line 162 "lexer.l"
{ printf("ERROR: expected\" \n");}
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 163 "lexer.l"
{ printf("ERROR: expected\" \n"); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 166 "lexer.l"
{ 
                                remove_char_from_str(yytext,temp1,'_');
                                num = atoi(temp1);
                                printf("Found decimal number %d\n", num);
                             }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 171 "lexer.l"
{
                                remove_char_from_str(yytext+2,temp1,'_');
                                num = atoi(temp1);
                                printf("Found decimal number %d\n", num);              
                             }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 177 "lexer.l"
{
                                        remove_char_from_str(yytext,temp1,'_');
                                        remove_char_from_str(temp1,temp2,'o');
                                        remove_char_from_str(temp2,temp1,'O');
                                        sscanf(temp1,"%o",&num);
                                        printf("Found octal number %d\n", num);
                                     }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 184 "lexer.l"
{
                                        remove_char_from_str(yytext + 2,temp1,'_');
                                        sscanf(temp1,"%x",&num);
                                        printf("Found hex number %d\n", num);
                                    }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 189 "lexer.l"
{
                                        remove_char_from_str(yytext + 2,temp1,'_');
                                        num = binstr_to_dec(temp1);
                                        printf("Found binary number %d\n", num); 
                                    }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 195 "lexer.l"
{
                                                                 remove_char_from_str(yytext,temp1,'_');
                                                                 real_num = atof(temp1);
                                                                 printf("Found float number %f\n", real_num); 
                                                            }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 201 "lexer.l"
{ printf("Found single-line comment: %s\n", yytext + 1); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 203 "lexer.l"
{ 
                                    // printf("Foun start ml-comment");
                                    comment[0] = 0; 
                                    BEGIN(ML_COMMENT);
                                }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 209 "lexer.l"
{
                                    strcat(comment, yytext + 5);
                                    printf("Found multi-line comment: %s\n", comment);
                                    BEGIN(INITIAL);
                                }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 215 "lexer.l"
{ 
                                    strcat(comment, yytext); 
                                }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 219 "lexer.l"
{
                                                printf("Found local variable or method name %s\n", yytext);
                                             }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 222 "lexer.l"
{
                                                             printf("Found instance variable %s\n", yytext);
                                                        }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 225 "lexer.l"
{
                                                 printf("Found class variable %s\n", yytext);
                                             }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 229 "lexer.l"
{
                                                printf("Found class name %s\n", yytext);
                                           }
	YY_BREAK
case 116:
/* rule 116 can match eol */
YY_RULE_SETUP
#line 233 "lexer.l"
{ //printf("Found new line\n"); 
        }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 235 "lexer.l"
ECHO;
	YY_BREAK
#line 1640 "lexer.flex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ML_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 265 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 265 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 264);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 235 "lexer.l"


void remove_char_from_str(const char * str, char * dest, char deleted_char) {
	int j = 0;
	
    for(int i = 0; str[i] != 0; i++) {
        if(str[i] != deleted_char) {
            dest[j++] = str[i];
        }
    }

    dest[j] = 0;
}

int binstr_to_dec(const char * str) {
    unsigned char *p = str;
    unsigned int   r = 0;

    while (p && *p ) {
        r <<= 1;
        r += (unsigned int)((*p++) & 0x01);
    }

    return (int) r;
}

void main(int argc, char **argv ){
	yyin = fopen(argv[1], "r" );

    yylex();
    return;
}

