#line 1 "lexer.flex.c"

#line 3 "lexer.flex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 125
#define YY_END_OF_BUFFER 126
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[351] =
    {   0,
        0,    0,  119,  119,    0,    0,  126,  125,  124,   68,
       84,  116,   41,   60,   71,   72,   39,   37,   80,   38,
       79,   40,  103,  103,   81,   83,   46,   53,   45,   78,
       77,  123,   75,   76,   62,  120,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,  120,
      120,  120,  120,   73,   61,   74,   63,   53,  119,  119,
       86,  102,   87,  125,   87,   44,  116,   58,   66,   42,
       56,   54,   55,   69,  114,    0,   57,    0,  107,    0,
        0,    0,    0,    0,    0,    0,  103,  103,  115,  104,
       82,   64,   48,   43,   47,   65,    0,  121,  123,    0,

      120,  120,  120,  120,  120,  120,  120,  120,  120,    9,
      120,  120,  120,  120,  120,   10,   17,  120,  120,  120,
      120,   22,  120,  120,  120,  120,  120,  120,  120,  120,
       67,    0,  119,  119,   86,   85,   98,   99,   97,   89,
       90,   95,   93,   88,   94,   96,   91,   92,  101,   59,
       70,  114,  114,  114,  113,  107,  108,  111,    0,  105,
        0,    0,  113,    0,  109,    0,  108,    0,    0,    0,
        0,    0,  113,  115,    0,    0,  104,  115,  115,  113,
        0,  103,  104,   49,   50,  122,  121,    0,  120,    2,
      120,  120,  120,  120,    7,  120,   13,  120,  120,  120,

      120,   16,  120,  120,   20,   21,  120,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  120,  120,    0,
      119,   99,  101,  100,    0,  114,    0,  107,  108,  111,
      112,  112,  105,  106,  106,  113,    0,  109,  110,  110,
      108,    0,    0,    0,  113,  113,  114,  115,  114,  113,
      104,  115,  113,  113,  115,  104,  122,    0,  120,  120,
      120,    5,  120,  120,   11,  120,  120,   51,  120,  120,
      120,   19,   23,  120,  120,  120,   27,  120,   29,   30,
      120,  120,  120,   34,  120,  120,    0,  118,   99,  100,
        0,  114,  113,  111,  112,  112,  105,  106,  106,  113,

      109,  110,  110,    0,  113,  114,  115,  115,  114,  114,
        0,  113,  113,    1,    3,    4,    6,  120,   12,  120,
      120,   15,  120,  120,   25,  120,   28,   31,  120,   33,
       35,   36,    0,  118,    0,  114,  114,  113,  120,   14,
       52,   18,   24,   26,   32,  117,  114,  120,    8,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    1,    6,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   27,   29,   30,   27,
       31,   31,   31,   31,   31,   31,   31,   31,   32,   31,
       31,   31,   31,   31,   31,   31,   31,   33,   31,   31,
       34,   35,   36,   37,   38,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   48,   49,   50,   51,   52,
       53,   54,   55,   56,   57,   58,   59,   60,   61,   62,
       63,   48,   64,   65,   66,   67,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[68] =
    {   0,
        1,    2,    1,    3,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    1,    6,    6,    6,    6,    1,
        1,    1,    1,    1,    1,    7,    6,    6,    6,    6,
        8,    8,    8,    1,    4,    1,    1,    9,   10,   10,
       10,   10,   10,   10,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,    4,    1,    3,    1
    } ;

static const flex_int16_t yy_base[370] =
    {   0,
        0,  947,  967,   66,   67,   71,  968, 1297, 1297,  937,
     1297,    0,  936,  951, 1297, 1297,   60,  934, 1297,  932,
       63,  931,  124,   74,  933, 1297,   62,  922,   63, 1297,
      918,    0, 1297, 1297, 1297,   60,   64,   80,   82,   81,
       93,   86,  929,  106,   91,  108,  104,   83,  116,  132,
       95,  135,  149, 1297,  877, 1297, 1297,   87,    0,  897,
        0, 1297,  875,  193, 1297, 1297,    0, 1297, 1297,  915,
     1297, 1297, 1297,  916,  154,  166, 1297,  182,  177,  174,
      188,  203,  201,  891,  240,  224,  247,  270,  293,  300,
     1297, 1297,  904,  904, 1297, 1297,    0,    0,    0,  308,

      911,  151,  155,  166,  189,   85,  173,  209,  215,  910,
      213,  278,  246,  221,  238,  909,  902,  232,  162,  233,
      217,  901,  287,  265,  267,  285,  115,  318,  319,  320,
     1297,  859,    0,  849,    0, 1297, 1297,  323, 1297, 1297,
     1297, 1297, 1297, 1297, 1297, 1297, 1297, 1297,  361, 1297,
      864,  333,  356,  368,  379,  394,  397,  391,  402,  407,
      419,  336,  425,  430,  838,  836,  433,  414,  436,  442,
      824,  448,  465,  471,  480,  503,  510,  518,  533,  543,
      549,  558,  581, 1297, 1297,    0,    0,  845,  328,  844,
      334,  344,  350,  342,  345,  459,  838,  402,   94,  461,

      413,  828,  479,  414,  827,  825,  284,  262,  499,  425,
      462,  463,  502,  511,  550,  497,  478,  406,  493,  786,
      780,  566,  609,    0,  591,  596,  604,  624,  627,  553,
      616,  630,  639,  653,  657,  662,  666,  763,  759,  758,
      670,  680,  687,  697,  715,  725,  732,  755,  762,  772,
      790,  800,  807,  830,  837,  847,    0,  770,  528,  564,
      490,  763,  603,  566,  746,  617,  653, 1297,  580,  592,
      652,  745,  710,  678,  649,  705,  706,  708,  590,  589,
      645,  650,  676,  588,  714,  679,  543,    0, 1297, 1297,
      865,  853,  870,  749,  796,  819,  876,  880,  888,  893,

      551,  493,  474,  903,  918,  933,  948,  963,  978,  993,
     1008, 1023, 1038,  420,  419,  407,  355,  724,  351,  740,
      722,  347,  768,  789,  343,  742,  283,  281,  738,  277,
      230,  211,  161,    0, 1053, 1068, 1083, 1098,  785,  165,
     1297,  101,   99,   97,   89, 1297, 1113,  815, 1297, 1297,
     1156, 1167, 1178, 1183, 1189, 1196, 1207, 1218, 1224, 1226,
     1232, 1243, 1249, 1254, 1259, 1265, 1270, 1275, 1285
    } ;

static const flex_int16_t yy_def[370] =
    {   0,
      350,    1,  351,  351,  352,  352,  350,  350,  350,  350,
      350,  353,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      354,  355,  350,  350,  350,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  350,  350,  350,  350,  350,  357,  357,
      358,  350,  350,  350,  350,  350,  353,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  359,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  360,  361,  355,  350,

      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      350,  350,  357,  357,  358,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  362,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  363,  364,  350,  350,  350,  350,
      364,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  365,  361,  350,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,

      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  350,
      357,  350,  362,  366,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  363,  367,  368,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  365,  350,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  350,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  350,  369,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,

      367,  368,  368,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  350,  369,  350,  350,  350,  350,  356,  356,
      350,  356,  356,  356,  356,  350,  350,  356,  350,    0,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350
    } ;

static const flex_int16_t yy_nxt[1365] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   24,   24,   25,
       26,   27,   28,   29,   30,   31,   32,   32,   32,   32,
       32,   32,   32,   33,    8,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   43,   44,   43,   43,   43,
       45,   46,   47,   43,   43,   48,   49,   50,   51,   43,
       52,   43,   53,   54,   55,   56,   57,    8,    8,   70,
       62,   63,    8,  100,   62,   63,   74,  350,   75,   75,
       75,   75,   71,   92,   93,   95,   96,   86,   60,   87,
       88,   88,   88,  350,  350,  350,  350,  102,  350,  350,

       76,   64,  350,   89,  350,   64,  350,  350,  350,   94,
      350,   90,  350,  103,  350,  104,   89,  350,  268,  350,
      107,  350,  105,  109,  114,  123,  132,  192,  350,  350,
       65,  108,   65,  110,   65,  106,   65,   78,  115,   79,
       79,   79,  111,  118,  112,  350,  128,  113,  350,  116,
      119,   80,   81,   82,  120,   83,   84,  117,  124,  122,
      121,   85,  350,   80,  100,   81,   82,  100,  350,  152,
      153,  153,  153,  213,  125,  350,   83,  126,  350,  350,
      129,   75,   75,   75,   75,   84,  350,  127,  102,  158,
      158,  154,  156,  156,  156,  130,  137,  155,  155,  155,

      155,  189,  350,   76,  160,  160,  160,  190,  138,  138,
      138,  159,  346,  162,  157,  162,   79,   79,   79,  163,
      163,  163,  350,  204,  350,  161,  350,  139,  350,  193,
      350,  140,  141,  191,  350,  142,  143,  172,  164,  173,
      173,  173,  173,  350,  144,  350,  350,  194,  145,  146,
      147,  350,  148,  174,  149,  167,  167,  167,  195,  350,
      176,  175,   87,   87,   87,   87,  174,  168,  169,  196,
      201,  170,  171,  203,  206,  350,   89,   85,  350,  168,
      350,  169,  205,   86,  177,   87,   88,   88,   88,   89,
      350,  350,  170,  202,  350,  199,  350,  350,  350,   89,

      350,  171,  274,  162,  200,  162,  178,   90,  179,  180,
      180,  180,   89,  181,  210,  182,  182,  182,  182,  197,
      211,  188,  174,   75,   75,   75,   75,  212,  207,  174,
      178,  350,  350,  350,  198,  174,  273,  183,  222,  222,
      222,  350,  174,  208,  209,   76,  100,  350,  152,  153,
      153,  153,  163,  163,  163,  350,  350,  350,  350,  214,
      350,  217,  219,  350,  350,  218,  259,  215,  350,  100,
      154,  152,  153,  153,  153,  216,  224,  224,  224,  224,
      260,  100,  261,  226,  226,  226,  226,  224,  224,  224,
      224,  264,  262,  154,  155,  155,  155,  155,  263,  224,

      224,  224,  224,  224,  224,  154,  230,  230,   82,  156,
      156,  156,  228,  228,  228,  350,  227,  232,  232,  350,
      350,   82,  233,  233,  233,  233,  350,  350,  231,  232,
      232,  157,  350,  350,  229,  235,  235,  235,  350,  159,
      236,  236,  236,  236,  234,  167,  167,  167,  241,  241,
      241,  159,  235,  235,  235,  285,  161,  167,  167,  167,
      267,  242,  237,  243,  243,  243,  243,  164,  277,  270,
      229,  272,  350,  161,  350,  350,  350,  174,  181,  164,
      245,  246,  246,  246,  178,  244,  179,  248,  248,  248,
      174,  350,  350,  244,   89,  249,  249,  249,  249,  269,

      174,  265,  247,  350,  278,  266,  350,   89,  178,  174,
      350,  302,  350,  174,  279,  350,  244,  175,  250,  250,
      250,  250,  174,  244,  350,  182,  182,  182,  182,  284,
      302,  178,  174,  179,  248,  248,  248,  271,  316,  174,
      244,  350,  286,  283,  280,  174,  178,  251,  179,  248,
      248,  248,  174,  281,  275,  178,  252,  276,  253,  254,
      254,  254,  172,  350,  249,  249,  249,  249,  230,  230,
      178,  176,  174,  182,  182,  182,  182,  350,  174,  350,
      255,  289,  289,  289,  314,  174,  175,   89,  239,  333,
      231,  174,  282,  350,  181,  177,  256,  256,  256,  256,

       89,  350,  350,  350,  291,  350,   75,   75,   75,   75,
      174,  226,  226,  226,  226,  315,  350,  318,  183,  293,
      293,  293,  293,  174,  350,  350,  350,  350,   76,  321,
      350,  294,  294,  292,  322,  350,  350,  350,  350,  228,
      228,  228,  241,  241,  241,  296,  296,  350,  350,  350,
      350,  350,  350,  295,  233,  233,  233,  233,  350,  317,
      319,  157,  350,  350,  229,  350,  350,  295,  297,  297,
      297,  297,  299,  299,  299,  299,  234,  236,  236,  236,
      236,  300,  300,  300,  300,  241,  241,  241,  328,  350,
      298,  350,  350,  304,  298,  243,  243,  243,  243,  237,

      244,  323,  243,  243,  243,  243,  329,  229,  320,  174,
      244,  325,  243,  243,  243,  243,  174,  244,  350,  350,
      332,  350,  174,  350,  244,  330,  174,  350,  181,  174,
      245,  246,  246,  246,  244,  350,  324,  350,  181,  174,
      245,  246,  246,  246,   89,  181,  341,  305,  305,  305,
      305,  350,  247,  350,   89,  350,  331,   89,  350,  350,
      326,  174,  247,  327,  294,  294,  339,   89,  252,  306,
      307,  308,  308,  308,  174,  181,  350,  309,  310,  310,
      310,  350,  340,  225,  174,  244,  231,  250,  250,  250,
      250,  174,  252,  344,  345,  302,  302,  174,  350,  306,

      239,   89,  350,  244,  174,  256,  256,  256,  256,  311,
      342,  296,  296,  252,   89,  307,  308,  308,  308,  174,
      252,  288,  253,  254,  254,  254,  348,  251,  350,  174,
      287,  343,  174,  295,  296,  296,  174,  252,  350,  349,
      350,  350,  174,  252,  255,  253,  254,  254,  254,  174,
      252,  350,  312,  313,  313,  313,  295,  350,  258,  174,
      244,  166,  256,  256,  256,  256,  174,  255,  226,  226,
      226,  226,  174,  166,  252,  239,  174,  225,  291,  174,
       75,   75,   75,   75,  251,  293,  293,  293,  293,  174,
      292,  297,  297,  297,  297,  299,  299,  299,  299,   82,

      221,  220,   76,  299,  299,  299,  299,  227,  300,  300,
      300,  300,   82,  234,  350,  350,  335,  298,  249,  249,
      249,  249,  350,  350,  350,  298,  185,  184,  166,  151,
      237,  244,  174,  305,  305,  305,  305,  150,  136,  134,
      175,  131,  350,   97,   94,  174,  181,   89,  337,  337,
      337,  337,   91,   77,   73,  336,   72,   69,   68,   66,
       89,  252,  174,  307,  308,  308,  308,  350,    8,   58,
      306,  350,  350,  350,  350,  174,  252,  174,  307,  308,
      308,  308,  350,  350,  350,  252,  350,  350,  350,  350,
      174,  181,  174,  309,  310,  310,  310,  350,  350,  350,

      252,  350,  350,  350,  350,  174,  181,  174,  309,  310,
      310,  310,  350,  350,  350,  306,  350,  350,  350,  350,
      174,  244,  174,  338,  338,  338,  338,  350,  350,  350,
      306,  350,  350,  350,  350,  174,  252,  174,  312,  313,
      313,  313,  350,  350,  350,  244,  350,  350,  350,  350,
      174,  252,  174,  312,  313,  313,  313,  350,  350,  350,
      255,  350,  350,  350,  350,  174,  335,  174,  249,  249,
      249,  249,  350,  350,  350,  255,  350,  350,  350,  350,
      174,  244,  174,  305,  305,  305,  305,  350,  350,  350,
      175,  350,  350,  350,  350,  174,  244,  174,  337,  337,

      337,  337,  350,  350,  350,  347,  350,  350,  350,  350,
      174,  244,  174,  338,  338,  338,  338,  350,  350,  350,
      347,  350,  350,  350,  350,  174,  244,   89,  337,  337,
      337,  337,  350,  350,  350,  311,  350,  350,  350,  350,
       89,  350,  174,  350,  350,  350,  350,  350,  350,  350,
      347,  350,  350,  350,  350,  174,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,   59,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   67,  350,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   98,
      350,   98,   98,   98,   99,  350,   99,   99,   99,   99,

      101,  101,  350,  101,  101,  101,  101,  133,  350,  133,
      133,  133,  133,  133,  133,  133,  133,  133,  135,  350,
      350,  350,  135,  135,  135,  135,  135,  135,  135,  165,
      350,  350,  165,  165,  186,  186,  186,  187,  350,  187,
      187,  187,  187,  223,  350,  350,  223,  223,  223,  223,
      223,  223,  223,  223,  238,  350,  350,  238,  238,  240,
      350,  350,  240,  240,  257,  350,  257,  257,  257,  257,
      290,  350,  350,  350,  290,  301,  350,  350,  301,  301,
      303,  350,  350,  303,  303,  334,  350,  334,  334,  334,
      334,  334,  334,  334,  334,  334,    7,  350,  350,  350,

      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350
    } ;

static const flex_int16_t yy_chk[1365] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    4,    5,   17,
        5,    5,    6,   36,    6,    6,   21,   37,   21,   21,
       21,   21,   17,   27,   27,   29,   29,   24,    4,   24,
       24,   24,   24,   38,   40,   39,   48,   36,  106,   42,

       21,    5,  345,   24,   45,    6,   41,  199,   51,   58,
      344,   24,  343,   37,  342,   37,   24,   47,  199,   44,
       39,   46,   38,   40,   42,   48,   58,  106,  127,   49,
        5,   39,    5,   40,    6,   38,    6,   23,   42,   23,
       23,   23,   41,   45,   41,   50,   51,   41,   52,   44,
       46,   23,   23,   23,   46,   23,   23,   44,   49,   47,
       46,   23,   53,   23,  102,   23,   23,   75,  103,   75,
       75,   75,   75,  127,   49,  119,   23,   50,  340,  104,
       52,   76,   76,   76,   76,   23,  107,   50,  102,   80,
       80,   75,   79,   79,   79,   53,   64,   78,   78,   78,

       78,  103,  105,   76,   81,   81,   81,  104,   64,   64,
       64,   80,  333,   82,   79,   82,   83,   83,   83,   82,
       82,   82,  108,  119,  332,   81,  111,   64,  109,  107,
      121,   64,   64,  105,  114,   64,   64,   86,   83,   86,
       86,   86,   86,  331,   64,  118,  120,  108,   64,   64,
       64,  115,   64,   86,   64,   85,   85,   85,  109,  113,
       87,   86,   87,   87,   87,   87,   86,   85,   85,  111,
      114,   85,   85,  118,  121,  208,   87,   85,  124,   85,
      125,   85,  120,   88,   87,   88,   88,   88,   88,   87,
      330,  112,   85,  115,  328,  113,  327,  207,  126,   88,

      123,   85,  208,   89,  113,   89,   89,   88,   89,   89,
       89,   89,   88,   90,  124,   90,   90,   90,   90,  112,
      125,  100,   89,  100,  100,  100,  100,  126,  123,   90,
       89,  128,  129,  130,  112,   89,  207,   90,  138,  138,
      138,  189,   90,  123,  123,  100,  152,  191,  152,  152,
      152,  152,  162,  162,  162,  194,  325,  192,  195,  128,
      322,  129,  130,  193,  319,  129,  189,  128,  317,  153,
      152,  153,  153,  153,  153,  128,  149,  149,  149,  149,
      191,  154,  192,  154,  154,  154,  154,  149,  149,  149,
      149,  195,  193,  153,  155,  155,  155,  155,  194,  149,

      149,  149,  149,  149,  149,  154,  158,  158,  155,  156,
      156,  156,  157,  157,  157,  198,  155,  159,  159,  218,
      316,  155,  160,  160,  160,  160,  201,  204,  158,  168,
      168,  156,  315,  314,  157,  161,  161,  161,  210,  159,
      163,  163,  163,  163,  160,  164,  164,  164,  167,  167,
      167,  168,  169,  169,  169,  218,  161,  170,  170,  170,
      198,  172,  163,  172,  172,  172,  172,  164,  210,  201,
      167,  204,  196,  169,  200,  211,  212,  172,  173,  170,
      173,  173,  173,  173,  174,  172,  174,  174,  174,  174,
      172,  217,  203,  175,  173,  175,  175,  175,  175,  200,

      174,  196,  173,  261,  211,  196,  219,  173,  174,  175,
      216,  303,  209,  174,  212,  213,  176,  175,  176,  176,
      176,  176,  175,  177,  214,  177,  177,  177,  177,  217,
      302,  178,  176,  178,  178,  178,  178,  203,  261,  177,
      176,  259,  219,  216,  213,  176,  179,  177,  179,  179,
      179,  179,  177,  214,  209,  178,  180,  209,  180,  180,
      180,  180,  181,  215,  181,  181,  181,  181,  230,  230,
      179,  182,  180,  182,  182,  182,  182,  260,  181,  264,
      180,  222,  222,  222,  259,  180,  181,  182,  301,  287,
      230,  181,  215,  269,  183,  182,  183,  183,  183,  183,

      182,  284,  280,  279,  225,  270,  225,  225,  225,  225,
      183,  226,  226,  226,  226,  260,  263,  264,  183,  227,
      227,  227,  227,  183,  223,  223,  223,  223,  225,  269,
      266,  231,  231,  226,  270,  223,  223,  223,  223,  228,
      228,  228,  229,  229,  229,  232,  232,  223,  223,  223,
      223,  223,  223,  231,  233,  233,  233,  233,  281,  263,
      266,  228,  275,  282,  229,  271,  267,  232,  234,  234,
      234,  234,  235,  235,  235,  235,  233,  236,  236,  236,
      236,  237,  237,  237,  237,  241,  241,  241,  281,  283,
      234,  274,  286,  242,  235,  242,  242,  242,  242,  236,

      243,  271,  243,  243,  243,  243,  282,  241,  267,  242,
      244,  275,  244,  244,  244,  244,  243,  242,  276,  277,
      286,  278,  242,  273,  243,  283,  244,  285,  245,  243,
      245,  245,  245,  245,  244,  321,  274,  318,  246,  244,
      246,  246,  246,  246,  245,  247,  321,  247,  247,  247,
      247,  329,  245,  320,  246,  326,  285,  245,  272,  265,
      276,  247,  246,  278,  294,  294,  318,  246,  248,  247,
      248,  248,  248,  248,  247,  249,  262,  249,  249,  249,
      249,  323,  320,  258,  248,  250,  294,  250,  250,  250,
      250,  249,  248,  326,  329,  240,  239,  248,  339,  249,

      238,  250,  324,  251,  249,  251,  251,  251,  251,  250,
      323,  295,  295,  252,  250,  252,  252,  252,  252,  251,
      253,  221,  253,  253,  253,  253,  339,  251,  348,  252,
      220,  324,  251,  295,  296,  296,  253,  252,  206,  348,
      205,  202,  252,  254,  253,  254,  254,  254,  254,  253,
      255,  197,  255,  255,  255,  255,  296,  190,  188,  254,
      256,  171,  256,  256,  256,  256,  255,  254,  292,  292,
      292,  292,  254,  166,  255,  165,  256,  151,  291,  255,
      291,  291,  291,  291,  256,  293,  293,  293,  293,  256,
      292,  297,  297,  297,  297,  298,  298,  298,  298,  293,

      134,  132,  291,  299,  299,  299,  299,  293,  300,  300,
      300,  300,  293,  297,  122,  117,  304,  298,  304,  304,
      304,  304,  116,  110,  101,  299,   94,   93,   84,   74,
      300,  305,  304,  305,  305,  305,  305,   70,   63,   60,
      304,   55,   43,   31,   28,  304,  306,  305,  306,  306,
      306,  306,   25,   22,   20,  305,   18,   14,   13,   10,
      305,  307,  306,  307,  307,  307,  307,    7,    3,    2,
      306,    0,    0,    0,    0,  306,  308,  307,  308,  308,
      308,  308,    0,    0,    0,  307,    0,    0,    0,    0,
      307,  309,  308,  309,  309,  309,  309,    0,    0,    0,

      308,    0,    0,    0,    0,  308,  310,  309,  310,  310,
      310,  310,    0,    0,    0,  309,    0,    0,    0,    0,
      309,  311,  310,  311,  311,  311,  311,    0,    0,    0,
      310,    0,    0,    0,    0,  310,  312,  311,  312,  312,
      312,  312,    0,    0,    0,  311,    0,    0,    0,    0,
      311,  313,  312,  313,  313,  313,  313,    0,    0,    0,
      312,    0,    0,    0,    0,  312,  335,  313,  335,  335,
      335,  335,    0,    0,    0,  313,    0,    0,    0,    0,
      313,  336,  335,  336,  336,  336,  336,    0,    0,    0,
      335,    0,    0,    0,    0,  335,  337,  336,  337,  337,

      337,  337,    0,    0,    0,  336,    0,    0,    0,    0,
      336,  338,  337,  338,  338,  338,  338,    0,    0,    0,
      337,    0,    0,    0,    0,  337,  347,  338,  347,  347,
      347,  347,    0,    0,    0,  338,    0,    0,    0,    0,
      338,    0,  347,    0,    0,    0,    0,    0,    0,    0,
      347,    0,    0,    0,    0,  347,  351,  351,  351,  351,
      351,  351,  351,  351,  351,  351,  351,  352,  352,  352,
      352,  352,  352,  352,  352,  352,  352,  352,  353,    0,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  354,
        0,  354,  354,  354,  355,    0,  355,  355,  355,  355,

      356,  356,    0,  356,  356,  356,  356,  357,    0,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  358,    0,
        0,    0,  358,  358,  358,  358,  358,  358,  358,  359,
        0,    0,  359,  359,  360,  360,  360,  361,    0,  361,
      361,  361,  361,  362,    0,    0,  362,  362,  362,  362,
      362,  362,  362,  362,  363,    0,    0,  363,  363,  364,
        0,    0,  364,  364,  365,    0,  365,  365,  365,  365,
      366,    0,    0,    0,  366,  367,    0,    0,  367,  367,
      368,    0,    0,  368,  368,  369,    0,  369,  369,  369,
      369,  369,  369,  369,  369,  369,  350,  350,  350,  350,

      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  350,  350,  350
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[126] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 6 "lexer.l"
	#include <stdio.h>
    #include "Grammar.tab.h"

    void remove_char_from_str(const char * str, char * dest, char deleted_char);
    int binstr_to_dec(const char * str);
#line 899 "lexer.flex.c"

#line 901 "lexer.flex.c"

#define INITIAL 0
#define ML_COMMENT 1
#define STRING 2

/*windows compatibility case*/
#include <io.h>
#define isatty _isatty
#define fileno _fileno
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 23 "lexer.l"



#line 27 "lexer.l"
    int num;
    float real_num;
    char temp1[100];
    char temp2[100];
    char comment[1000];
    char string[1000];
    int nestingCount = 0;


#line 1134 "lexer.flex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 351 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 350 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 36 "lexer.l"
{ return ALIAS_KEYWORD; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 37 "lexer.l"
{ return AND_KEYWORD; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 38 "lexer.l"
{ return BEGIN_KEYWORD; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 39 "lexer.l"
{ return BREAK_KEYWORD; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 40 "lexer.l"
{ return CASE_KEYWORD; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 41 "lexer.l"
{ return CLASS_KEYWORD; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 42 "lexer.l"
{ return DEF_KEYWORD; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 43 "lexer.l"
{ return DEFINED_KEYWORD; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 44 "lexer.l"
{ return DO_KEYWORD; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 45 "lexer.l"
{ return IF_KEYWORD; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 46 "lexer.l"
{ return ELSE_KEYWORD; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 47 "lexer.l"
{ return ELSIF_KEYWORD; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 48 "lexer.l"
{ return END_KEYWORD; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 49 "lexer.l"
{ return ENSURE_KEYWORD; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 50 "lexer.l"
{ return FALSE_KEYWORD; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 51 "lexer.l"
{ return FOR_KEYWORD; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 52 "lexer.l"
{ return IN_KEYWORD; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 53 "lexer.l"
{ return MODULE_KEYWORD; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 54 "lexer.l"
{ return NEXT_KEYWORD; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 55 "lexer.l"
{ return NIL_KEYWORD; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 56 "lexer.l"
{ return NOT_KEYWORD; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 57 "lexer.l"
{ return OR_KEYWORD; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 58 "lexer.l"
{ return REDO_KEYWORD; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 59 "lexer.l"
{ return RESCUE_KEYWORD; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 60 "lexer.l"
{ return RETRY_KEYWORD; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 61 "lexer.l"
{ return RETURN_KEYWORD; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 62 "lexer.l"
{ return SELF_KEYWORD; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 63 "lexer.l"
{ return SUPER_KEYWORD; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 64 "lexer.l"
{ return THEN_KEYWORD; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 65 "lexer.l"
{ return TRUE_KEYWORD; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 66 "lexer.l"
{ return UNDEF_KEYWORD; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 67 "lexer.l"
{ return UNLESS_KEYWORD; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 68 "lexer.l"
{ return UNTIL_KEYWORD; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 69 "lexer.l"
{ return WHEN_KEYWORD; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 70 "lexer.l"
{ return WHILE_KEYWORD; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 71 "lexer.l"
{ return YIELD_KEYWORD; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 73 "lexer.l"
{ return ARITHMETIC_PLUS_OP; }   
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 74 "lexer.l"
{ return ARITHMETIC_MINUS_OP; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 75 "lexer.l"
{ return ARITHMETIC_MUL_OP; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 76 "lexer.l"
{ return ARITHMETIC_DIV_OP; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 77 "lexer.l"
{ return ARITHMETIC_MOD_OP; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 78 "lexer.l"
{ return ARITHMETIC_POW_OP; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 80 "lexer.l"
{ return EQL_OP; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 81 "lexer.l"
{ return NOT_EQL_OP; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 82 "lexer.l"
{ return GREATER_OP; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 83 "lexer.l"
{ return LESS_OP; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 84 "lexer.l"
{ return GREATER_OR_EQL_OP; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 85 "lexer.l"
{ return LESS_OR_EQL_OP; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 86 "lexer.l"
{ return COMB_COMPRASION_OP; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 87 "lexer.l"
{ return CASE_EQL_OP; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 88 "lexer.l"
{ return RECEIVER_EQL_OP; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 89 "lexer.l"
{ return OBJ_ID_EQL_OP; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 91 "lexer.l"
{ return ASSIGN_OP; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 92 "lexer.l"
{ return ADD_ASSIGN_OP; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 93 "lexer.l"
{ return SUB_ASSIGN_OP; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 94 "lexer.l"
{ return MUL_ASSIGN_OP; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 95 "lexer.l"
{ return DIV_ASSIGN_OP; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 96 "lexer.l"
{ return MOD_ASSIGN_OP; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 97 "lexer.l"
{ return POW_ASSIGN_OP; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 99 "lexer.l"
{ return BIN_AND_OP; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 100 "lexer.l"
{ return BIN_OR_OP; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 101 "lexer.l"
{ return BIN_XOR_OP; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 102 "lexer.l"
{ return BIN_ONES_COMPLEMENT_OP; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 103 "lexer.l"
{ return BIN_LEFT_SHIFT_OP; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 104 "lexer.l"
{ return BIN_RIGHT_SHIFT_OP; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 106 "lexer.l"
{ return LOGICAL_AND_OP; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 107 "lexer.l"
{ return LOGICAL_OR_OP; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 108 "lexer.l"
{ return LOGICAL_NOT_OP; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 110 "lexer.l"
{ return INCLUSIVE_RANGE_OP; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 111 "lexer.l"
{ return EXCLUSIVE_RANGE_OP; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 113 "lexer.l"
{ return OPEN_ROUND_BRACKET; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 114 "lexer.l"
{ return CLOSE_ROUND_BRACKET; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 115 "lexer.l"
{ return OPEN_CURLY_BRACKET; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 116 "lexer.l"
{
                if(nestingCount == 0) {
                    return CLOSE_CURLY_BRACKET;
                } else {
                    nestingCount--;
                    BEGIN(STRING);
                    string[0] = 0;
                    return ARITHMETIC_PLUS_OP;
                }
            }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 126 "lexer.l"
{ return OPEN_SQUARE_BRACKET; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 127 "lexer.l"
{ return CLOSE_SQUARE_BRACKET; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 128 "lexer.l"
{ return COMMERCIAL_AT; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 130 "lexer.l"
{ return QUESTION_SYMBOL; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 132 "lexer.l"
{ return DOT_SYMBOL; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 133 "lexer.l"
{ return COMMA_SYMBOL; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 134 "lexer.l"
{ return COLON_SYMBOL; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 135 "lexer.l"
{ return DOUBLE_COLON_SYMBOL;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 136 "lexer.l"
{ return SEMICOLON_SYMBOL; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 138 "lexer.l"
{ 
                string[0] = 0; 
                BEGIN(STRING);    
            }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 143 "lexer.l"
{ 
                        printf("Found string %s\n", string);
                        printf("Found ARITHMETIC_PLUS_OP\n");
                        nestingCount++;
                        BEGIN(INITIAL);
                    }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 149 "lexer.l"
{ strcat(string, yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 150 "lexer.l"
{ strcat(string, yytext); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 151 "lexer.l"
{ strcat(string, "\n"); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 152 "lexer.l"
{ strcat(string, "\a"); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 153 "lexer.l"
{ strcat(string, "\b"); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 154 "lexer.l"
{ strcat(string, "\t"); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 155 "lexer.l"
{ strcat(string, "\v"); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 156 "lexer.l"
{ strcat(string, "\f"); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 157 "lexer.l"
{ strcat(string, "\r"); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 158 "lexer.l"
{ strcat(string, "\e"); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 159 "lexer.l"
{ strcat(string, " "); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 160 "lexer.l"
{ strcat(string, "\\"); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 161 "lexer.l"
{ strcat(string, "\""); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 162 "lexer.l"
{ 
                                sscanf(yytext + 1, "%o", &num);
                                temp1[0] = (char) num;
                                temp1[1] = 0;
                                strcat(string, temp1);
                            }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 169 "lexer.l"
{ 
                                sscanf(yytext + 2, "%x", &num);
                                temp1[0] = (char) num;
                                temp1[1] = 0;
                                strcat(string, temp1);
                            }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 175 "lexer.l"
{ printf("ERROR: Invalid hex escape \n"); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 177 "lexer.l"
{ 
                /* printf("Found string %s \n", string); */
                yylval.string_un=(char *)malloc(strlen(string)+1);
                strcpy(yylval.string_un, string);
                BEGIN(INITIAL);
                return STR;
            }
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 184 "lexer.l"
{ printf("ERROR: expected\" \n"); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 186 "lexer.l"
{ 
                                remove_char_from_str(yytext,temp1,'_');
                                yylval.int_un = atoi(temp1);
                                return INTEGER_NUMBER;
                             }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 192 "lexer.l"
{ printf("Found decimal number error1 %s\n", yytext); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 194 "lexer.l"
{
                                remove_char_from_str(yytext+2,temp1,'_');
                                yylval.int_un = atoi(temp1);
                                return INTEGER_NUMBER;              
                             }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 200 "lexer.l"
{ printf("Found decimal number error2 %s\n", yytext); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 202 "lexer.l"
{
                                        remove_char_from_str(yytext,temp1,'_');
                                        remove_char_from_str(temp1,temp2,'o');
                                        remove_char_from_str(temp2,temp1,'O');
                                        sscanf(temp1,"%o",&num);
                                        yylval.int_un = num;
                                        return INTEGER_NUMBER;
                                     }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 211 "lexer.l"
{ printf("Found oct number error %s\n", yytext); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 213 "lexer.l"
{
                                        remove_char_from_str(yytext + 2,temp1,'_');
                                        sscanf(temp1,"%x",&num);
                                        yylval.int_un = num;
                                        return INTEGER_NUMBER;
                                    }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 220 "lexer.l"
{ printf("Found hex number error %s\n", yytext); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 222 "lexer.l"
{
                                        remove_char_from_str(yytext + 2,temp1,'_');
                                        num = binstr_to_dec(temp1);
                                        yylval.int_un = num;
                                        return INTEGER_NUMBER; 
                                    }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 229 "lexer.l"
{ printf("Found bin number error %s\n", yytext); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 233 "lexer.l"
{
                                                                 remove_char_from_str(yytext,temp1,'_');
                                                                 real_num = atof(temp1);
                                                                 return FLOAT_NUMBER; 
                                                            }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 239 "lexer.l"
{ printf("Found float number error1 %s\n", yytext); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 241 "lexer.l"
{ printf("Found float number error2 %s\n", yytext); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 245 "lexer.l"
{ printf("Found single-line comment: %s\n", yytext + 1); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 247 "lexer.l"
{ 
                                    // printf("Foun start ml-comment");
                                    comment[0] = 0; 
                                    BEGIN(ML_COMMENT);
                                }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 253 "lexer.l"
{
                                    strcat(comment, yytext + 5);
                                    printf("Found multi-line comment: %s\n", comment);
                                    BEGIN(INITIAL);
                                }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 259 "lexer.l"
{ 
                                    strcat(comment, yytext); 
                                }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 263 "lexer.l"
{
                                                yylval.string_un=(char *)malloc(strlen(yytext)+1);
                                                strcpy(yylval.string_un, yytext); 
                                                return VAR_METHOD_NAME;
                                             }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 268 "lexer.l"
{
                                                             yylval.string_un=(char *)malloc(strlen(yytext)+1);
                                                             strcpy(yylval.string_un, yytext); 
                                                             return INSTANCE_VAR_NAME;
                                                        }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 273 "lexer.l"
{
                                                 return CLASS_VAR_NAME;
                                             }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 277 "lexer.l"
{
                                                return CLASS_NAME;
                                           }
	YY_BREAK
case 124:
/* rule 124 can match eol */
YY_RULE_SETUP
#line 281 "lexer.l"
{ return NEW_LINE_SYMBOL;
        }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 283 "lexer.l"
ECHO;
	YY_BREAK
#line 1913 "lexer.flex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ML_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 351 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 351 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 350);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 283 "lexer.l"


void remove_char_from_str(const char * str, char * dest, char deleted_char) {
	int j = 0;
	
    for(int i = 0; str[i] != 0; i++) {
        if(str[i] != deleted_char) {
            dest[j++] = str[i];
        }
    }

    dest[j] = 0;
}

int binstr_to_dec(const char * str) {
    unsigned char *p = str;
    unsigned int   r = 0;

    while (p && *p ) {
        r <<= 1;
        r += (unsigned int)((*p++) & 0x01);
    }

    return (int) r;
}


