#line 1 "lexer.flex.c"

#line 3 "lexer.flex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 126
#define YY_END_OF_BUFFER 127
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[348] =
    {   0,
        0,    0,  120,  120,    0,    0,  127,  126,  125,   68,
       84,  117,   41,   60,   71,   72,   39,   37,   81,   38,
       80,   40,  104,  104,   82,   83,   46,   53,   45,   79,
      124,   75,   76,   62,  121,  121,  121,  121,  121,  121,
      121,  121,  121,  121,  121,  121,  121,  121,  121,  121,
      121,  121,   73,   61,   74,   63,   53,  120,  120,   86,
      103,  102,   87,  126,   87,   44,  117,   58,   66,   42,
       56,   54,   55,   69,  115,    0,   57,    0,  108,    0,
        0,    0,    0,    0,    0,    0,  104,  104,  116,  105,
       64,   48,   43,   47,   65,    0,  122,  124,    0,  121,

      121,  121,  121,  121,  121,  121,  121,  121,    9,  121,
      121,  121,  121,  121,   10,   17,  121,  121,  121,  121,
       22,  121,  121,  121,  121,  121,  121,  121,  121,   67,
        0,  120,  120,   86,   85,   98,   99,   97,   89,   90,
       95,   93,   88,   94,   96,   91,   92,  101,   59,   70,
      115,  115,  115,  114,  108,  109,  112,    0,  106,    0,
        0,  114,    0,  110,    0,  109,    0,    0,    0,    0,
        0,  114,  116,    0,    0,  105,  116,  116,  114,    0,
      104,  105,   49,   50,  123,  122,    0,  121,    2,  121,
      121,  121,  121,    7,  121,   13,  121,  121,  121,  121,

       16,  121,  121,   20,   21,  121,  121,  121,  121,  121,
      121,  121,  121,  121,  121,  121,  121,  121,    0,  120,
       99,  101,  100,    0,  115,    0,  108,  109,  112,  113,
      113,  106,  107,  107,  114,    0,  110,  111,  111,  109,
        0,    0,    0,  114,  114,  115,  116,  115,  114,  105,
      116,  114,  114,  116,  105,  123,    0,  121,  121,  121,
        5,  121,  121,   11,  121,  121,   51,  121,  121,  121,
       19,   23,  121,  121,  121,   27,  121,   29,   30,  121,
      121,  121,   34,  121,  121,    0,  119,   99,  100,  115,
      114,  112,  113,  113,  106,  107,  107,  114,  110,  111,

      111,    0,  114,  115,  116,  116,  115,  115,    0,  114,
      114,    1,    3,    4,    6,  121,   12,  121,  121,   15,
      121,  121,   25,  121,   28,   31,  121,   33,   35,   36,
        0,  119,  115,  115,  114,  121,   14,   52,   18,   24,
       26,   32,  118,  115,  121,    8,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    1,    6,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       18,   18,   18,   18,   18,   19,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   27,   29,   30,   27,
       31,   31,   31,   31,   31,   31,   31,   31,   32,   31,
       31,   31,   31,   31,   31,   31,   31,   33,   31,   31,
       34,   35,   36,   37,   38,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   48,   49,   50,   51,   52,
       53,   54,   55,   56,   57,   58,   59,   60,   61,   62,
       63,   48,   64,   65,   66,   67,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[68] =
    {   0,
        1,    2,    1,    3,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    1,    6,    6,    6,    6,    1,
        1,    1,    1,    1,    1,    7,    6,    6,    6,    6,
        8,    8,    8,    1,    4,    1,    1,    9,   10,   10,
       10,   10,   10,   10,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,    4,    1,    3,    1
    } ;

static const flex_int16_t yy_base[367] =
    {   0,
        0,  920,  940,   66,   67,   71,  941, 1279, 1279,  907,
     1279,    0,  906,  921, 1279, 1279,   60,  898, 1279,  897,
       63,  895,  124,   74, 1279, 1279,   62,  894,   63,  890,
        0, 1279, 1279, 1279,   60,   64,   80,   82,   81,   93,
       86,  900,  106,   91,  108,  104,   83,  116,  132,   95,
      135,  149, 1279,  848, 1279, 1279,   87,    0,  847,    0,
     1279, 1279,  825,  193, 1279, 1279,    0, 1279, 1279,  865,
     1279, 1279, 1279,  872,  154,  166, 1279,  182,  177,  174,
      188,  203,  201,  847,  240,  224,  247,  270,  293,  300,
     1279,  859,  858, 1279, 1279,    0,    0,    0,  308,  862,

      151,  155,  166,  189,   85,  173,  209,  215,  853,  213,
      278,  246,  221,  238,  852,  851,  232,  162,  233,  217,
      843,  287,  265,  267,  285,  115,  318,  319,  320, 1279,
      812,    0,  801,    0, 1279, 1279,  323, 1279, 1279, 1279,
     1279, 1279, 1279, 1279, 1279, 1279, 1279,  361, 1279,  333,
      356,  368,  379,  391,  395,  398,  402,  406,  408,  413,
      336,  431,  421,  813,  810,  425,  436,  437,  444,  793,
      454,  469,  484,  499,  514,  529,  522,  537,  547,  562,
      577,  592, 1279, 1279,    0,    0,  804,  328,  796,  334,
      344,  385,  378,  431,  462,  792,  406,   94,  450,  453,

      766,  452,  463,  764,  761,  284,  262,  467,  476,  465,
      443,  482,  492,  544,  444,  510,  520,  536,  717,  714,
      566,  620,    0,  585,  608,  600,  596,  615,  627,  635,
      638,  650,  661,  665,  673,  677,  705,  700,  684,  669,
      696,  702,  711,  734,  741,  751,  769,  779,  786,  809,
      816,  826,  844,  854,  861,    0,  884,  583,  656,  607,
      703,  584,  657,  691,  505,  644, 1279,  683,  614,  687,
      631,  575,  615,  661,  688,  574,  690,  560,  559,  628,
      709,  692,  557,  733,  721,  522,    0, 1279, 1279,  877,
      889,  775,  798,  803,  893,  907,  917,  921,  530,  456,

      442,  930,  947,  953,  962,  985,  992, 1002, 1020, 1030,
     1037,  355,  351,  350,  347,  747,  345,  768,  479,  343,
      794,  807,  342,  684,  283,  281,  717,  277,  230,  211,
      161,    0, 1060, 1067, 1077,  759,  165, 1279,  101,   99,
       97,   89, 1279, 1095,  824, 1279, 1279, 1138, 1149, 1160,
     1165, 1171, 1178, 1189, 1200, 1206, 1208, 1214, 1225, 1231,
     1236, 1241, 1247, 1252, 1257, 1267
    } ;

static const flex_int16_t yy_def[367] =
    {   0,
      347,    1,  348,  348,  349,  349,  347,  347,  347,  347,
      347,  350,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  351,
      352,  347,  347,  347,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  347,  347,  347,  347,  347,  354,  354,  355,
      347,  347,  347,  347,  347,  347,  350,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  356,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  357,  358,  352,  347,  353,

      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  347,
      347,  354,  354,  355,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  359,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  360,  361,  347,  347,  347,  347,  361,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  362,  358,  347,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,

      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  347,  354,
      347,  359,  363,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  360,  364,  365,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  362,  347,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  347,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  347,  366,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  364,  365,

      365,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      353,  353,  353,  353,  353,  353,  353,  353,  353,  353,
      347,  366,  347,  347,  347,  353,  353,  347,  353,  353,
      353,  353,  347,  347,  353,  347,    0,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347
    } ;

static const flex_int16_t yy_nxt[1347] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   24,   24,   25,
       26,   27,   28,   29,    8,   30,   31,   31,   31,   31,
       31,   31,   31,   32,    8,   33,   34,   35,   36,   37,
       38,   39,   40,   41,   42,   42,   43,   42,   42,   42,
       44,   45,   46,   42,   42,   47,   48,   49,   50,   42,
       51,   42,   52,   53,   54,   55,   56,    8,   61,   70,
       62,   63,   61,   99,   62,   63,   74,  347,   75,   75,
       75,   75,   71,   91,   92,   94,   95,   86,   59,   87,
       88,   88,   88,  347,  347,  347,  347,  101,  347,  347,

       76,   64,  347,   89,  347,   64,  347,  347,  347,   93,
      347,   90,  347,  102,  347,  103,   89,  347,  267,  347,
      106,  347,  104,  108,  113,  122,  131,  191,  347,  347,
       65,  107,   65,  109,   65,  105,   65,   78,  114,   79,
       79,   79,  110,  117,  111,  347,  127,  112,  347,  115,
      118,   80,   81,   82,  119,   83,   84,  116,  123,  121,
      120,   85,  347,   80,   99,   81,   82,   99,  347,  151,
      152,  152,  152,  212,  124,  347,   83,  125,  347,  347,
      128,   75,   75,   75,   75,   84,  347,  126,  101,  157,
      157,  153,  155,  155,  155,  129,  136,  154,  154,  154,

      154,  188,  347,   76,  159,  159,  159,  189,  137,  137,
      137,  158,  343,  161,  156,  161,   79,   79,   79,  162,
      162,  162,  347,  203,  347,  160,  347,  138,  347,  192,
      347,  139,  140,  190,  347,  141,  142,  171,  163,  172,
      172,  172,  172,  347,  143,  347,  347,  193,  144,  145,
      146,  347,  147,  173,  148,  166,  166,  166,  194,  347,
      175,  174,   87,   87,   87,   87,  173,  167,  168,  195,
      200,  169,  170,  202,  205,  347,   89,   85,  347,  167,
      347,  168,  204,   86,  176,   87,   88,   88,   88,   89,
      347,  347,  169,  201,  347,  198,  347,  347,  347,   89,

      347,  170,  273,  161,  199,  161,  177,   90,  178,  179,
      179,  179,   89,  180,  209,  181,  181,  181,  181,  196,
      210,  187,  173,   75,   75,   75,   75,  211,  206,  173,
      177,  347,  347,  347,  197,  173,  272,  182,  221,  221,
      221,  347,  173,  207,  208,   76,  224,  347,   75,   75,
       75,   75,  162,  162,  162,  347,  347,  347,  347,  213,
      347,  216,  218,  347,  347,  217,  258,  214,  347,   99,
       76,  151,  152,  152,  152,  215,  223,  223,  223,  223,
      259,   99,  260,  151,  152,  152,  152,  223,  223,  223,
      223,  347,   99,  153,  225,  225,  225,  225,  347,  223,

      223,  223,  223,  223,  223,  153,  154,  154,  154,  154,
      155,  155,  155,  227,  227,  227,  153,  229,  229,  347,
       82,  231,  231,  232,  232,  232,  232,  261,  226,  234,
      234,  234,  156,   82,  262,  228,  166,  166,  166,  230,
      240,  240,  240,  158,  347,  233,  235,  235,  235,  235,
      160,  231,  231,  234,  234,  234,  347,  347,  163,  166,
      166,  166,  228,  347,  266,  347,  347,  241,  236,  242,
      242,  242,  242,  158,  160,  347,  347,  263,  347,  300,
      347,  163,  180,  173,  244,  245,  245,  245,  268,  347,
      282,  243,  347,  300,  278,  347,  173,  177,   89,  178,

      247,  247,  247,  338,  264,  347,  246,  277,  265,  269,
      270,   89,  243,  173,  248,  248,  248,  248,  347,  276,
      271,  177,  274,  347,  279,  275,  173,  243,  173,  249,
      249,  249,  249,  347,  280,  177,  174,  178,  247,  247,
      247,  173,  243,  173,  181,  181,  181,  181,  317,  347,
      177,  243,  178,  247,  247,  247,  173,  347,  173,  177,
      251,  283,  252,  253,  253,  253,  250,  238,  331,  284,
      347,  173,  347,  347,  177,  171,  173,  248,  248,  248,
      248,  288,  288,  288,  254,  285,  281,  347,  347,  173,
      175,  173,  181,  181,  181,  181,  347,  347,  224,  174,

       75,   75,   75,   75,  173,  180,   89,  255,  255,  255,
      255,  227,  227,  227,  176,  291,  291,  291,  291,   89,
      347,  173,   76,  225,  225,  225,  225,  347,  347,  182,
      240,  240,  240,  156,  173,  347,  347,  347,  347,  312,
      315,  347,  229,  229,  347,  290,  347,  347,  347,  347,
      292,  292,  228,  294,  294,  314,  320,  347,  347,  347,
      347,  347,  347,  347,  230,  232,  232,  232,  232,  347,
      347,  326,  293,  322,  347,  293,  295,  295,  295,  295,
      297,  297,  297,  297,  240,  240,  240,  233,  235,  235,
      235,  235,  298,  298,  298,  298,  347,  347,  296,  318,

      347,  347,  296,  347,  347,  347,  228,  313,  316,  302,
      236,  248,  248,  248,  248,  243,  347,  242,  242,  242,
      242,  300,  347,  323,  243,  173,  242,  242,  242,  242,
      347,  173,  319,  174,  347,  341,  321,  300,  173,  243,
      173,  328,  238,  324,  173,  325,  347,  180,  243,  244,
      245,  245,  245,  173,  180,  287,  244,  245,  245,  245,
      347,  286,  330,   89,  180,  327,  303,  303,  303,  303,
       89,  246,  347,  342,  347,  329,   89,  347,  246,  347,
      173,  347,  251,   89,  305,  306,  306,  306,  304,  336,
      292,  292,  180,  173,  307,  308,  308,  308,  173,  243,

      345,  249,  249,  249,  249,  347,  251,  347,  173,  347,
      337,  173,  230,  294,  294,   89,  304,  257,  294,  294,
      347,  173,  243,  309,  255,  255,  255,  255,   89,  251,
      165,  305,  306,  306,  306,  293,  339,  347,  173,  251,
      293,  252,  253,  253,  253,  173,  250,  165,  346,  340,
      238,  173,  220,  251,  219,  173,  347,  251,  173,  252,
      253,  253,  253,  254,  347,  347,  347,  251,  173,  310,
      311,  311,  311,  173,  243,  347,  255,  255,  255,  255,
      184,  254,  183,  173,  165,  150,  173,  149,  135,  133,
      173,  251,  225,  225,  225,  225,  173,  224,  250,   75,

       75,   75,   75,  173,  291,  291,  291,  291,  295,  295,
      295,  295,  130,  347,  290,   96,   93,   77,   82,   73,
       72,   76,  297,  297,  297,  297,  226,   69,   68,   66,
      233,   82,  297,  297,  297,  297,  298,  298,  298,  298,
      347,    8,   57,  302,  296,  248,  248,  248,  248,  347,
      347,  347,  347,  347,  296,  347,  347,  347,  236,  173,
      243,  347,  303,  303,  303,  303,  180,  174,  334,  334,
      334,  334,  173,  347,  347,  251,   89,  305,  306,  306,
      306,  347,  173,  347,  333,  347,  347,  347,  347,   89,
      304,  173,  347,  347,  347,  173,  347,  347,  251,  251,

      305,  306,  306,  306,  173,  180,  347,  307,  308,  308,
      308,  347,  347,  347,  173,  180,  347,  307,  308,  308,
      308,  173,  251,  347,  347,  347,  347,  173,  347,  304,
      347,  173,  347,  243,  173,  335,  335,  335,  335,  304,
      347,  347,  347,  251,  173,  310,  311,  311,  311,  173,
      251,  347,  310,  311,  311,  311,  347,  243,  347,  173,
      347,  347,  173,  347,  347,  347,  173,  254,  347,  347,
      347,  347,  173,  243,  254,  303,  303,  303,  303,  173,
      243,  347,  334,  334,  334,  334,  347,  347,  347,  173,
      243,  347,  335,  335,  335,  335,  173,  344,  347,  347,

      347,  347,  173,  347,  344,  347,   89,  347,  243,  173,
      334,  334,  334,  334,  309,  347,  347,  347,  347,   89,
      347,  347,  347,  347,  173,  347,  347,  347,  347,  347,
      347,  347,  344,  347,  347,  347,  347,  173,   58,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       67,  347,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   97,  347,   97,   97,   97,   98,  347,   98,   98,
       98,   98,  100,  100,  347,  100,  100,  100,  100,  132,
      347,  132,  132,  132,  132,  132,  132,  132,  132,  132,

      134,  347,  347,  347,  134,  134,  134,  134,  134,  134,
      134,  164,  347,  347,  164,  164,  185,  185,  185,  186,
      347,  186,  186,  186,  186,  222,  347,  347,  222,  222,
      222,  222,  222,  222,  222,  222,  237,  347,  347,  237,
      237,  239,  347,  347,  239,  239,  256,  347,  256,  256,
      256,  256,  289,  347,  347,  347,  289,  299,  347,  347,
      299,  299,  301,  347,  347,  301,  301,  332,  347,  332,
      332,  332,  332,  332,  332,  332,  332,  332,    7,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347
    } ;

static const flex_int16_t yy_chk[1347] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    4,    5,   17,
        5,    5,    6,   35,    6,    6,   21,   36,   21,   21,
       21,   21,   17,   27,   27,   29,   29,   24,    4,   24,
       24,   24,   24,   37,   39,   38,   47,   35,  105,   41,

       21,    5,  342,   24,   44,    6,   40,  198,   50,   57,
      341,   24,  340,   36,  339,   36,   24,   46,  198,   43,
       38,   45,   37,   39,   41,   47,   57,  105,  126,   48,
        5,   38,    5,   39,    6,   37,    6,   23,   41,   23,
       23,   23,   40,   44,   40,   49,   50,   40,   51,   43,
       45,   23,   23,   23,   45,   23,   23,   43,   48,   46,
       45,   23,   52,   23,  101,   23,   23,   75,  102,   75,
       75,   75,   75,  126,   48,  118,   23,   49,  337,  103,
       51,   76,   76,   76,   76,   23,  106,   49,  101,   80,
       80,   75,   79,   79,   79,   52,   64,   78,   78,   78,

       78,  102,  104,   76,   81,   81,   81,  103,   64,   64,
       64,   80,  331,   82,   79,   82,   83,   83,   83,   82,
       82,   82,  107,  118,  330,   81,  110,   64,  108,  106,
      120,   64,   64,  104,  113,   64,   64,   86,   83,   86,
       86,   86,   86,  329,   64,  117,  119,  107,   64,   64,
       64,  114,   64,   86,   64,   85,   85,   85,  108,  112,
       87,   86,   87,   87,   87,   87,   86,   85,   85,  110,
      113,   85,   85,  117,  120,  207,   87,   85,  123,   85,
      124,   85,  119,   88,   87,   88,   88,   88,   88,   87,
      328,  111,   85,  114,  326,  112,  325,  206,  125,   88,

      122,   85,  207,   89,  112,   89,   89,   88,   89,   89,
       89,   89,   88,   90,  123,   90,   90,   90,   90,  111,
      124,   99,   89,   99,   99,   99,   99,  125,  122,   90,
       89,  127,  128,  129,  111,   89,  206,   90,  137,  137,
      137,  188,   90,  122,  122,   99,  150,  190,  150,  150,
      150,  150,  161,  161,  161,  323,  320,  191,  317,  127,
      315,  128,  129,  314,  313,  128,  188,  127,  312,  151,
      150,  151,  151,  151,  151,  127,  148,  148,  148,  148,
      190,  152,  191,  152,  152,  152,  152,  148,  148,  148,
      148,  193,  153,  151,  153,  153,  153,  153,  192,  148,

      148,  148,  148,  148,  148,  152,  154,  154,  154,  154,
      155,  155,  155,  156,  156,  156,  153,  157,  157,  197,
      154,  158,  158,  159,  159,  159,  159,  192,  154,  160,
      160,  160,  155,  154,  193,  156,  163,  163,  163,  157,
      166,  166,  166,  158,  194,  159,  162,  162,  162,  162,
      160,  167,  167,  168,  168,  168,  211,  215,  163,  169,
      169,  169,  166,  199,  197,  202,  200,  171,  162,  171,
      171,  171,  171,  167,  168,  195,  203,  194,  210,  301,
      208,  169,  172,  171,  172,  172,  172,  172,  199,  209,
      215,  171,  319,  300,  211,  212,  171,  173,  172,  173,

      173,  173,  173,  319,  195,  213,  172,  210,  195,  200,
      202,  172,  174,  173,  174,  174,  174,  174,  265,  209,
      203,  173,  208,  216,  212,  208,  173,  175,  174,  175,
      175,  175,  175,  217,  213,  177,  174,  177,  177,  177,
      177,  174,  176,  175,  176,  176,  176,  176,  265,  218,
      178,  175,  178,  178,  178,  178,  175,  214,  176,  177,
      179,  216,  179,  179,  179,  179,  176,  299,  286,  217,
      283,  176,  279,  278,  178,  180,  179,  180,  180,  180,
      180,  221,  221,  221,  179,  218,  214,  276,  272,  179,
      181,  180,  181,  181,  181,  181,  258,  262,  224,  180,

      224,  224,  224,  224,  180,  182,  181,  182,  182,  182,
      182,  227,  227,  227,  181,  226,  226,  226,  226,  181,
      260,  182,  224,  225,  225,  225,  225,  269,  273,  182,
      228,  228,  228,  227,  182,  222,  222,  222,  222,  258,
      262,  280,  229,  229,  271,  225,  222,  222,  222,  222,
      230,  230,  228,  231,  231,  260,  269,  266,  222,  222,
      222,  222,  222,  222,  229,  232,  232,  232,  232,  259,
      263,  280,  230,  273,  274,  231,  233,  233,  233,  233,
      234,  234,  234,  234,  240,  240,  240,  232,  235,  235,
      235,  235,  236,  236,  236,  236,  268,  324,  233,  266,

      270,  275,  234,  277,  264,  282,  240,  259,  263,  241,
      235,  241,  241,  241,  241,  242,  261,  242,  242,  242,
      242,  239,  281,  274,  243,  241,  243,  243,  243,  243,
      327,  242,  268,  241,  285,  324,  270,  238,  241,  242,
      243,  282,  237,  275,  242,  277,  284,  244,  243,  244,
      244,  244,  244,  243,  245,  220,  245,  245,  245,  245,
      316,  219,  285,  244,  246,  281,  246,  246,  246,  246,
      245,  244,  336,  327,  205,  284,  244,  204,  245,  201,
      246,  318,  247,  245,  247,  247,  247,  247,  246,  316,
      292,  292,  248,  246,  248,  248,  248,  248,  247,  249,

      336,  249,  249,  249,  249,  196,  247,  321,  248,  189,
      318,  247,  292,  293,  293,  249,  248,  187,  294,  294,
      322,  248,  250,  249,  250,  250,  250,  250,  249,  251,
      170,  251,  251,  251,  251,  293,  321,  345,  250,  252,
      294,  252,  252,  252,  252,  251,  250,  165,  345,  322,
      164,  250,  133,  251,  131,  252,  121,  253,  251,  253,
      253,  253,  253,  252,  116,  115,  109,  254,  252,  254,
      254,  254,  254,  253,  255,  100,  255,  255,  255,  255,
       93,  253,   92,  254,   84,   74,  253,   70,   63,   59,
      255,  254,  290,  290,  290,  290,  254,  257,  255,  257,

      257,  257,  257,  255,  291,  291,  291,  291,  295,  295,
      295,  295,   54,   42,  290,   30,   28,   22,  291,   20,
       18,  257,  296,  296,  296,  296,  291,   14,   13,   10,
      295,  291,  297,  297,  297,  297,  298,  298,  298,  298,
        7,    3,    2,  302,  296,  302,  302,  302,  302,    0,
        0,    0,    0,    0,  297,    0,    0,    0,  298,  302,
      303,    0,  303,  303,  303,  303,  304,  302,  304,  304,
      304,  304,  302,    0,    0,  305,  303,  305,  305,  305,
      305,    0,  304,    0,  303,    0,    0,    0,    0,  303,
      304,  305,    0,    0,    0,  304,    0,    0,  306,  305,

      306,  306,  306,  306,  305,  307,    0,  307,  307,  307,
      307,    0,    0,    0,  306,  308,    0,  308,  308,  308,
      308,  307,  306,    0,    0,    0,    0,  306,    0,  307,
        0,  308,    0,  309,  307,  309,  309,  309,  309,  308,
        0,    0,    0,  310,  308,  310,  310,  310,  310,  309,
      311,    0,  311,  311,  311,  311,    0,  309,    0,  310,
        0,    0,  309,    0,    0,    0,  311,  310,    0,    0,
        0,    0,  310,  333,  311,  333,  333,  333,  333,  311,
      334,    0,  334,  334,  334,  334,    0,    0,    0,  333,
      335,    0,  335,  335,  335,  335,  334,  333,    0,    0,

        0,    0,  333,    0,  334,    0,  335,    0,  344,  334,
      344,  344,  344,  344,  335,    0,    0,    0,    0,  335,
        0,    0,    0,    0,  344,    0,    0,    0,    0,    0,
        0,    0,  344,    0,    0,    0,    0,  344,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  349,
      349,  349,  349,  349,  349,  349,  349,  349,  349,  349,
      350,    0,  350,  350,  350,  350,  350,  350,  350,  350,
      350,  351,    0,  351,  351,  351,  352,    0,  352,  352,
      352,  352,  353,  353,    0,  353,  353,  353,  353,  354,
        0,  354,  354,  354,  354,  354,  354,  354,  354,  354,

      355,    0,    0,    0,  355,  355,  355,  355,  355,  355,
      355,  356,    0,    0,  356,  356,  357,  357,  357,  358,
        0,  358,  358,  358,  358,  359,    0,    0,  359,  359,
      359,  359,  359,  359,  359,  359,  360,    0,    0,  360,
      360,  361,    0,    0,  361,  361,  362,    0,  362,  362,
      362,  362,  363,    0,    0,    0,  363,  364,    0,    0,
      364,  364,  365,    0,    0,  365,  365,  366,    0,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,

      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347,  347,  347,  347,  347,
      347,  347,  347,  347,  347,  347
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[127] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 1, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexer.l"
#line 6 "lexer.l"
	#include <stdio.h>

    void remove_char_from_str(const char * str, char * dest, char deleted_char);
    int binstr_to_dec(const char * str);
#line 894 "lexer.flex.c"

#line 896 "lexer.flex.c"

#define INITIAL 0
#define ML_COMMENT 1
#define STRING 2

/*windows compatibility case*/
#include <io.h>
#define isatty _isatty
#define fileno _fileno
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 22 "lexer.l"



#line 26 "lexer.l"
    int num;
    float real_num;
    char temp1[100];
    char temp2[100];
    char comment[1000];
    char string[1000];
    int nestingCount = 0;


#line 1129 "lexer.flex.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 348 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 347 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 35 "lexer.l"
{ printf("Found ALIAS_KEYWORD\n"); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 36 "lexer.l"
{ printf("Found AND_KEYWORD\n"); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 37 "lexer.l"
{ printf("Found BEGIN_KEYWORD\n"); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 38 "lexer.l"
{ printf("Found BREAK_KEYWORD\n"); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 39 "lexer.l"
{ printf("Found CASE_KEYWORD\n"); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 40 "lexer.l"
{ printf("Found CLASS_KEYWORD\n"); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 41 "lexer.l"
{ printf("Found DEF_KEYWORD\n"); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 42 "lexer.l"
{ printf("Found DEFINED_KEYWORD\n"); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 43 "lexer.l"
{ printf("Found DO_KEYWORD\n"); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 44 "lexer.l"
{ printf("Found IF_KEYWORD\n"); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 45 "lexer.l"
{ printf("Found ELSE_KEYWORD\n"); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 46 "lexer.l"
{ printf("Found ELSIF_KEYWORD\n"); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 47 "lexer.l"
{ printf("Found END_KEYWORD\n"); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 48 "lexer.l"
{ printf("Found ENSURE_KEYWORD\n"); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 49 "lexer.l"
{ printf("Found FALSE_KEYWORD\n"); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 50 "lexer.l"
{ printf("Found FOR_KEYWORD\n"); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 51 "lexer.l"
{ printf("Found IN_KEYWORD\n"); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 52 "lexer.l"
{ printf("Found MODULE_KEYWORD\n"); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 53 "lexer.l"
{ printf("Found NEXT_KEYWORD\n"); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 54 "lexer.l"
{ printf("Found NIL_KEYWORD\n"); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 55 "lexer.l"
{ printf("Found NOT_KEYWORD\n"); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 56 "lexer.l"
{ printf("Found OR_KEYWORD\n"); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 57 "lexer.l"
{ printf("Found REDO_KEYWORD\n"); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 58 "lexer.l"
{ printf("Found RESCUE_KEYWORD\n"); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 59 "lexer.l"
{ printf("Found RETRY_KEYWORD\n"); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 60 "lexer.l"
{ printf("Found RETURN_KEYWORD\n"); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 61 "lexer.l"
{ printf("Found SELF_KEYWORD\n"); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 62 "lexer.l"
{ printf("Found SUPER_KEYWORD\n"); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 63 "lexer.l"
{ printf("Found THEN_KEYWORD\n"); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 64 "lexer.l"
{ printf("Found TRUE_KEYWORD\n"); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 65 "lexer.l"
{ printf("Found UNDEF_KEYWORD\n"); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 66 "lexer.l"
{ printf("Found UNLESS_KEYWORD\n"); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 67 "lexer.l"
{ printf("Found UNTIL_KEYWORD\n"); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 68 "lexer.l"
{ printf("Found WHEN_KEYWORD\n"); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 69 "lexer.l"
{ printf("Found WHILE_KEYWORD\n"); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 70 "lexer.l"
{ printf("Found YIELD_KEYWORD\n"); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 72 "lexer.l"
{ printf("Found ARITHMETIC_PLUS_OP\n"); }   
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 73 "lexer.l"
{ printf("Found ARITHMETIC_MINUS_OP\n"); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 74 "lexer.l"
{ printf("Found ARITHMETIC_MUL_OP\n"); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 75 "lexer.l"
{ printf("Found ARITHMETIC_DIV_OP\n"); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 76 "lexer.l"
{ printf("Found ARITHMETIC_MOD_OP\n"); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 77 "lexer.l"
{ printf("Found ARITHMETIC_POW_OP\n"); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 79 "lexer.l"
{ printf("Found EQL_OP\n"); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 80 "lexer.l"
{ printf("Found NOT_EQL_OP\n"); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 81 "lexer.l"
{ printf("Found GREATER_OP\n"); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 82 "lexer.l"
{ printf("Found LESS_OP\n"); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 83 "lexer.l"
{ printf("Found GREATER_OR_EQL_OP\n"); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 84 "lexer.l"
{ printf("Found LESS_OR_EQL_OP\n"); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 85 "lexer.l"
{ printf("Found COMB_COMPRASION_OP\n"); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 86 "lexer.l"
{ printf("Found CASE_EQL_OP\n"); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 87 "lexer.l"
{ printf("Found RECEIVER_EQL_OP\n"); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 88 "lexer.l"
{ printf("Found OBJ_ID_EQL_OP\n"); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 90 "lexer.l"
{ printf("Found ASSIGN_OP\n"); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 91 "lexer.l"
{ printf("Found ADD_ASSIGN_OP\n"); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 92 "lexer.l"
{ printf("Found SUB_ASSIGN_OP\n"); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 93 "lexer.l"
{ printf("Found MUL_ASSIGN_OP\n"); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 94 "lexer.l"
{ printf("Found DIV_ASSIGN_OP\n"); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 95 "lexer.l"
{ printf("Found MOD_ASSIGN_OP\n"); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 96 "lexer.l"
{ printf("Found POW_ASSIGN_OP\n"); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 98 "lexer.l"
{ printf("Found BIN_AND_OP\n"); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 99 "lexer.l"
{ printf("Found BIN_OR_OP\n"); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 100 "lexer.l"
{ printf("Found BIN_XOR_OP\n"); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 101 "lexer.l"
{ printf("Found BIN_ONES_COMPLEMENT_OP\n"); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 102 "lexer.l"
{ printf("Found BIN_LEFT_SHIFT_OP\n"); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 103 "lexer.l"
{ printf("Found BIN_RIGHT_SHIFT_OP\n"); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 105 "lexer.l"
{ printf("Found LOGICAL_AND_OP\n"); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 106 "lexer.l"
{ printf("Found LOGICAL_OR_OP\n"); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 107 "lexer.l"
{ printf("Found LOGICAL_NOT_OP\n"); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 109 "lexer.l"
{ printf("Found INCLUSIVE_RANGE_OP\n"); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 110 "lexer.l"
{ printf("Found EXCLUSIVE_RANGE_OP\n"); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 112 "lexer.l"
{ printf("Found OPEN_ROUND_BRACKET\n"); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 113 "lexer.l"
{ printf("Found CLOSE_ROUND_BRACKET\n"); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 114 "lexer.l"
{ printf("Found OPEN_CURLY_BRACKET\n"); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 115 "lexer.l"
{
                if(nestingCount == 0) {
                    printf("Found CLOSE_CURLY_BRACKET\n");
                } else {
                    nestingCount--;
                    BEGIN(STRING);
                    string[0] = 0;
                    printf("Found ARITHMETIC_PLUS_OP\n");
                }
            }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 125 "lexer.l"
{ printf("Found OPEN_SQUARE_BRACKET\n"); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 126 "lexer.l"
{ printf("Found CLOSE_SQUARE_BRACKET\n"); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 127 "lexer.l"
{ printf("Found OPEN_ANGLE_BRACKET\n"); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 128 "lexer.l"
{ printf("Found CLOSE_ANGLE_BRACKET\n"); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 129 "lexer.l"
{ printf("Found COMMERCIAL_AT\n"); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 131 "lexer.l"
{ printf("Found DOT SYMBOL\n"); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 132 "lexer.l"
{ printf("Found COMMA SYMBOL\n"); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 133 "lexer.l"
{ printf("Found COLON SYMBOL\n"); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 134 "lexer.l"
{ printf("Found SEMICOLON SYMBOL\n"); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 136 "lexer.l"
{ 
                string[0] = 0; 
                BEGIN(STRING);    
            }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 141 "lexer.l"
{ 
                        printf("Found string %s\n", string);
                        printf("Found ARITHMETIC_PLUS_OP\n");
                        nestingCount++;
                        BEGIN(INITIAL);
                    }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 147 "lexer.l"
{ strcat(string, yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 148 "lexer.l"
{ strcat(string, yytext); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 149 "lexer.l"
{ strcat(string, "\n"); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 150 "lexer.l"
{ strcat(string, "\a"); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 151 "lexer.l"
{ strcat(string, "\b"); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 152 "lexer.l"
{ strcat(string, "\t"); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 153 "lexer.l"
{ strcat(string, "\v"); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 154 "lexer.l"
{ strcat(string, "\f"); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 155 "lexer.l"
{ strcat(string, "\r"); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 156 "lexer.l"
{ strcat(string, "\e"); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 157 "lexer.l"
{ strcat(string, " "); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 158 "lexer.l"
{ strcat(string, "\\"); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 159 "lexer.l"
{ strcat(string, "\""); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 160 "lexer.l"
{ 
                                sscanf(yytext + 1, "%o", &num);
                                temp1[0] = (char) num;
                                temp1[1] = 0;
                                strcat(string, temp1);
                            }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 167 "lexer.l"
{ 
                                sscanf(yytext + 2, "%x", &num);
                                temp1[0] = (char) num;
                                temp1[1] = 0;
                                strcat(string, temp1);
                            }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 173 "lexer.l"
{ printf("ERROR: Invalid hex escape \n"); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 175 "lexer.l"
{ 
                printf("Found string %s \n", string);
                BEGIN(INITIAL);
            }
	YY_BREAK
case 103:
/* rule 103 can match eol */
YY_RULE_SETUP
#line 179 "lexer.l"
{ printf("ERROR: expected\" \n");}
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 180 "lexer.l"
{ printf("ERROR: expected\" \n"); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 182 "lexer.l"
{ 
                                remove_char_from_str(yytext,temp1,'_');
                                num = atoi(temp1);
                                printf("Found decimal number %d\n", num);
                             }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 188 "lexer.l"
{ printf("Found decimal number error1 %s\n", yytext); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 190 "lexer.l"
{
                                remove_char_from_str(yytext+2,temp1,'_');
                                num = atoi(temp1);
                                printf("Found decimal number %d\n", num);              
                             }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 196 "lexer.l"
{ printf("Found decimal number error2 %s\n", yytext); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 198 "lexer.l"
{
                                        remove_char_from_str(yytext,temp1,'_');
                                        remove_char_from_str(temp1,temp2,'o');
                                        remove_char_from_str(temp2,temp1,'O');
                                        sscanf(temp1,"%o",&num);
                                        printf("Found octal number %d\n", num);
                                     }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 206 "lexer.l"
{ printf("Found oct number error %s\n", yytext); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 208 "lexer.l"
{
                                        remove_char_from_str(yytext + 2,temp1,'_');
                                        sscanf(temp1,"%x",&num);
                                        printf("Found hex number %d\n", num);
                                    }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 214 "lexer.l"
{ printf("Found hex number error %s\n", yytext); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 216 "lexer.l"
{
                                        remove_char_from_str(yytext + 2,temp1,'_');
                                        num = binstr_to_dec(temp1);
                                        printf("Found binary number %d\n", num); 
                                    }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 222 "lexer.l"
{ printf("Found bin number error %s\n", yytext); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 226 "lexer.l"
{
                                                                 remove_char_from_str(yytext,temp1,'_');
                                                                 real_num = atof(temp1);
                                                                 printf("Found float number %f\n", real_num); 
                                                            }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 232 "lexer.l"
{ printf("Found float number error1 %s\n", yytext); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 234 "lexer.l"
{ printf("Found float number error2 %s\n", yytext); }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 238 "lexer.l"
{ printf("Found single-line comment: %s\n", yytext + 1); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 240 "lexer.l"
{ 
                                    // printf("Foun start ml-comment");
                                    comment[0] = 0; 
                                    BEGIN(ML_COMMENT);
                                }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 246 "lexer.l"
{
                                    strcat(comment, yytext + 5);
                                    printf("Found multi-line comment: %s\n", comment);
                                    BEGIN(INITIAL);
                                }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 252 "lexer.l"
{ 
                                    strcat(comment, yytext); 
                                }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 256 "lexer.l"
{
                                                printf("Found local variable or method name %s\n", yytext);
                                             }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 259 "lexer.l"
{
                                                             printf("Found instance variable %s\n", yytext);
                                                        }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 262 "lexer.l"
{
                                                 printf("Found class variable %s\n", yytext);
                                             }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 266 "lexer.l"
{
                                                printf("Found class name %s\n", yytext);
                                           }
	YY_BREAK
case 125:
/* rule 125 can match eol */
YY_RULE_SETUP
#line 270 "lexer.l"
{ //printf("Found new line\n"); 
        }
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 272 "lexer.l"
ECHO;
	YY_BREAK
#line 1904 "lexer.flex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(ML_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 348 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 348 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 347);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');
	if ( YY_CURRENT_BUFFER_LVALUE->yy_at_bol )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 272 "lexer.l"


void remove_char_from_str(const char * str, char * dest, char deleted_char) {
	int j = 0;
	
    for(int i = 0; str[i] != 0; i++) {
        if(str[i] != deleted_char) {
            dest[j++] = str[i];
        }
    }

    dest[j] = 0;
}

int binstr_to_dec(const char * str) {
    unsigned char *p = str;
    unsigned int   r = 0;

    while (p && *p ) {
        r <<= 1;
        r += (unsigned int)((*p++) & 0x01);
    }

    return (int) r;
}

void main(int argc, char **argv ){
	yyin = fopen(argv[1], "r" );

    yylex();
    return;
}

